Repository Adyen/adyen-ios, pull requests merged in 2022-12, with the labels that each got.

#1088 Adds a github action to validate every PR labels and potentially release notes
  .github/workflows/cancel-duplicate-work-flows.yml
  .github/workflows/validate_pr_labels_and_release_notes.yml
  .pull-requests-allowed-labels-list
Labels: chore

#1094 fixed: ListSectionHeaderStyle is not applied to stored payment method and Issuers'list background color
  Adyen/UI/View Controllers/SearchViewController.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenDropIn/Utilities/ComponentManager.swift
Labels: fixed

#1095 Update renovate.json
  renovate.json
Labels: chore

#1091 Demo app Testflight job update
  .github/workflows/publish-demo-app.yml
  Adyen.xcodeproj/project.pbxproj
  Scripts/publish-demo-app.sh
Labels: chore

#1096 Adds a script to collect all release notes since the last release
  .github/workflows/get_release_notes.yml
  .github/workflows/validate_pr_labels_and_release_notes.yml
Labels: chore

#1098 Update obsolete docs
  AdyenComponents/Apple Pay/ApplePayConfiguration.swift
Labels: chore

#1103 v4: Make DropInComponent a LoadingComponent
  AdyenDropIn/DropInComponent.swift
  Demo/Common/Networking/PaymentsRequest.swift
Labels: new

#1106 Make DropInComponent a LoadingComponent
  AdyenDropIn/DropInComponent.swift
Labels: new

#1109 test DA flow in the scripts that tests package managers integration
  Adyen.xcodeproj/project.pbxproj
  Scripts/test-CocoaPods-integration.sh
  Scripts/test-SPM-integration.sh
  Scripts/test-carthage-integration.sh
  Tests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDSResultExtension.swift
Labels: chore
