Repository Adyen/adyen-ios, pull requests merged in 2023-07, with the labels that each got.

#1265 Update CardEncryptor.swift
  AdyenEncryption/CardEncryptor.swift
Labels: chore

#1270 Use GITHUB_TOKEN for CI jobs
  .github/workflows/build.yml
  .github/workflows/cancel-duplicate-work-flows.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/format_project.yml
  .github/workflows/pr_scan.yml
  .github/workflows/publish-demo-app.yml
  .github/workflows/regenerate-docs.yml
  .github/workflows/spell-check.yml
  .github/workflows/test-SPM-integration.yml
  .github/workflows/test-carthage-integration.yml
  .github/workflows/test_cocoapods_integration.yml
  .github/workflows/update-version.yml
Labels: chore

#1272 Added settings for card component
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/CardComponentConfiguration.swift
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/IntegrationExamples/Components/CardComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/Networking/SessionRequest.swift
  Demo/Configuration.swift
  Demo/SwiftUI/PaymentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
Labels: chore

#1262 chore: Adding loading state to SearchViewController
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/AdyenAssets.xcassets/search.imageset/Contents.json
  Adyen/Assets/AdyenAssets.xcassets/search.imageset/Search Small@1x.png
  Adyen/Assets/AdyenAssets.xcassets/search.imageset/Search Small@2x.png
  Adyen/Assets/AdyenAssets.xcassets/search.imageset/Search Small@3x.png
  Adyen/Assets/AdyenAssets.xcassets/search.imageset/search.pdf
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/View Controllers/SearchViewController.swift
  Adyen/UI/View Controllers/SearchViewController/SearchViewController+InterfaceState.swift
  Adyen/UI/View Controllers/SearchViewController/SearchViewController+ViewModel.swift
  Adyen/UI/View Controllers/SearchViewController/SearchViewController.swift
  Adyen/Utilities/BundleSPMExtension.swift
  Adyen/Utilities/KeyboardObserver.swift
  Adyen/Utilities/Non SPM Bundle Extension/CoreBundleExtension.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenComponents/Issuer List/IssuerListEmptyView.swift
  AdyenDropIn/Presentation/DropInNavigationController.swift
  Tests/Adyen Tests/UI/Form/FormItems/Selectable/FormSelectableItemViewTests.swift
  Tests/Adyen Tests/UI/SearchViewControllerTests.swift
  Tests/Adyen Tests/Utilities/KeyboardObserverTests.swift
  Tests/Components Tests/IssuerList/IssuerListComponentTests.swift
  UITests/Components/IssuerList/IssuerListComponentUITests.swift
Labels: chore

#1267 chore: Form address item configuration
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Components/AbstractPersonalInformationComponent/AddressFormItemInjector.swift
  Adyen/UI/Form/Items/Address/AddressStyle.swift
  Adyen/UI/Form/Items/Address/FormAddressItem+Configuration.swift
  Adyen/UI/Form/Items/Address/FormFullAddressItem.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  Demo/Configuration.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressItemTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Card Tests/Items/CardNumberItem/FormItemViewBuilderTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
Labels: chore

#1260 Dev 64080: delegated authentication delete api integration
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/Components/3DS2/ThreeDSResult.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2DAScreenPresenterMock.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: new

#1273 chore: Introducing LinkTextView
  Adyen.xcodeproj/project.pbxproj
  Adyen/Helpers/StringHelpers.swift
  Adyen/UI/Form/Items/Basic Items/FormAttributedLabelItem.swift
  Adyen/UI/Views/LinkTextView.swift
  AdyenComponents/OnlineBanking/OnlineBankingComponent.swift
  Tests/Adyen Tests/UI/Views/LinkTextViewTests.swift
  Tests/Adyen Tests/UI/Views/LoadingViewTests.swift
  UITests/Components/Online Banking/OnlineBankingComponentUITests.swift
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testContinueButtonLoading-iPhone12.initial_state.png
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testContinueButtonLoading-iPhone12.initial_state.txt
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testContinueButtonLoading-iPhone12.stopped_loading.png
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testContinueButtonLoading-iPhone12.stopped_loading.txt
Labels: chore

#1266 chore: add skip validation to testflight job
  .github/workflows/publish-demo-app.yml
  Adyen.xcodeproj/project.pbxproj
  Scripts/publish-demo-app.sh
Labels: chore

#1274 chore: Added api version check for storePaymentMethod switch
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Networking/SessionRequest.swift
  Demo/Configuration.swift
Labels: chore

#1277 feature: new session delegate with session result
  Adyen.xcodeproj/project.pbxproj
  AdyenSession/API/Payments/PaymentsRequest.swift
  AdyenSession/API/Session Setup/SessionSetupRequest.swift
  AdyenSession/API/SessionAPIClient.swift
  AdyenSession/AdyenSession+ActionComponentDelegate.swift
  AdyenSession/AdyenSession+PaymentComponentDelegate.swift
  AdyenSession/AdyenSession.swift
  AdyenSession/AdyenSessionDelegate.swift
  AdyenSession/AdyenSessionResult.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Tests/Session Tests/SessionDelegateMock.swift
  Tests/Session Tests/SessionTests.swift
Labels: new, deprecated

#1259 feature: Add enforced locale init for LocalizationParameters
  Adyen/Utilities/Localization.swift
  Adyen/Utilities/LocalizationParameters.swift
  Tests/Adyen Tests/Utilities/LocalizationTests.swift
  spell-check-word-allow-list.yaml
Labels: new

#1278 Fix amount locale formatting
  Adyen/Utilities/Localization.swift
  Tests/Adyen Tests/Utilities/LocalizationTests.swift
  Tests/Card Tests/CardComponentTests.swift
Labels: new

#1276 feature: Full screen country picker
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Components/AbstractPersonalInformationComponent/AddressFormItemInjector.swift
  Adyen/Core/Core Protocols/ViewControllerPresenter.swift
  Adyen/UI/Form/FormItemViewBuilder.swift
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/Form/Items/Address/FormAddressItem.swift
  Adyen/UI/Form/Items/Address/FormRegionPickerItem.swift
  Adyen/UI/Form/Items/Address/Lookup/FormAddressLookupItem.swift
  Adyen/UI/Form/Items/Address/Lookup/FormAddressLookupItemView.swift
  Adyen/UI/Form/Items/Basic Items/FormVerticalStackItemView.swift
  Adyen/UI/Form/Items/Phone Number/FormPhoneNumberItemView.swift
  Adyen/UI/Form/Items/Text/TextField.swift
  Adyen/UI/Form/Items/Value Pickers/FormRegionPickerItem.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerItem.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerItemView.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerSearchViewController+EmptyView+Style.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerSearchViewController+EmptyView.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerSearchViewController+Style.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerSearchViewController.swift
  Adyen/UI/Form/Items/Value/Selectable/FormSelectableValueItemView.swift
  Adyen/UI/List/ListItem+Icon.swift
  Adyen/UI/List/ListItem.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupViewController+Style.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressLookupFormViewController.swift
  Adyen/UI/View Controllers/AddressLookup/Search/AddressLookupSearchViewController+Style.swift
  Adyen/UI/View Controllers/AddressLookup/Search/AddressLookupSearchViewController.swift
  Adyen/UI/View Controllers/SearchViewController/SearchViewController.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenCashAppPay/CashAppPayComponent.swift
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  AdyenComponents/BACS Direct Debit/Scenes/Confirmation/BACSConfirmationViewController.swift
  AdyenComponents/BACS Direct Debit/Scenes/Input/BACSInputFormViewController.swift
  AdyenComponents/BLIK/BLIKComponent.swift
  AdyenComponents/OnlineBanking/OnlineBankingComponent.swift
  AdyenComponents/SEPA Direct Debit/SEPADirectDebitComponent.swift
  AdyenComponents/UPI/UPIComponent.swift
  AdyenDropIn/Components/PreselectedPaymentMethodComponent.swift
  AdyenSwiftUI/Present View Controller/FullScreenViewControllerPresenter.swift
  Demo/Common/IntegrationExamples/AddressLookupProvider.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressItemTests.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressLookupItemTests.swift
  Tests/Adyen Tests/UI/Form/FormItems/Picker/FormPickerItemTests.swift
  Tests/Adyen Tests/UI/Form/FormItems/Selectable/FormSelectableItemViewTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressLookupViewControllerTests.swift
  Tests/Adyen Tests/UI/View Controllers/FormPickerSearchViewControllerTests.swift
  Tests/Adyen Tests/Utilities/AssertsTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Card Tests/Items/CardNumberItem/FormItemViewBuilderTests.swift
  Tests/DummyData/PostalAddressMocks.swift
  Tests/Helpers/XCTestCase+FormAddressItem.swift
  UITests/Components/Atome/AtomeComponentUITests.swift
  spell-check-excluded-files-list
Labels: new

#1281 Resolve reference loop
  Demo/UIKit/ComponentsViewController.swift
Labels: chore

#1264 chore: Create Localization.md
  Adyen.docc/Localization.md
Labels: chore

#1280 chore: Add applePayDelegate to demo app
  Demo/Common/IntegrationExamples/Components/ApplePayComponentAdvancedFlowExample.swift
Labels: chore

#1282 chore: Fixing flaky tests
  Tests/Card Tests/CardComponentTests.swift
  Tests/Components Tests/Boleto/BoletoComponentTests.swift
Labels: chore

#1284 Fix Sonar warning
  .github/workflows/pr_scan.yml
Labels: chore

#1269 COIOS-593: ThreeDS Opaque error handling - Adding support to V4
  .github/workflows/build.yml
  .github/workflows/format_project.yml
  .github/workflows/pr_scan.yml
  .github/workflows/publich_podspec.yml
  .github/workflows/publish-demo-app.yml
  .github/workflows/regenerate-docs.yml
  .github/workflows/spell-check.yml
  .github/workflows/test-SPM-integration.yml
  .github/workflows/test-carthage-integration.yml
  .github/workflows/test_cocoapods_integration.yml
  .github/workflows/update-version.yml
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/3DS2/Action handlers/AnyThreeDS2ActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2ClassicActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2CompactActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Fingerprint Submitter/ThreeDS2FingerprintSubmitter.swift
  AdyenActions/Components/3DS2/ThreeDS2Component.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprint.swift
  AdyenActions/Components/3DS2/ThreeDSResult.swift
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Demo/Configuration.swift
  Package.swift
  Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
  Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
Labels: new

#1247 COIOS 593: ThreeDS Opaque error handling
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/3DS2/3DS2 SDK Adapters/AnyChallengeResult.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprint.swift
  AdyenActions/Components/3DS2/ThreeDSResult.swift
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
  Tests/Card Tests/3DS2 Component/AnyThreeDS2ActionHandlerMock.swift
  Tests/Card Tests/3DS2 Component/AnyThreeDS2FingerprintSubmitterMock.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: new

#1286 Added dropIn settings
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/Configuration/DropInSettingsView.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Configuration.swift
Labels: chore

#1292 chore: Fixing SwiftUI target frameworks
  Adyen.xcodeproj/project.pbxproj
Labels: fixed
