Repository Adyen/adyen-ios, pull requests merged in 2023-05, with the labels that each got.

#1201 Added card component using session
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/IntegrationExamples/Components/CardComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/SwiftUI/PaymentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
Labels: chore

#1198 Update 3ds2sdk release 2.3.1
  .github/workflows/test-carthage-integration.yml
  .github/workflows/test_cocoapods_integration.yml
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/3DS2/3DS2 SDK Adapters/AnyChallengeResult.swift
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Demo/Configuration.swift
  Package.swift
  Scripts/test-carthage-integration.sh
  Tests/AdyenTests/Card Tests/3DS2 Component/AnyADYServiceMock.swift
Labels: changed

#1208 Fixing SwiftUI interface for iPad
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/SwiftUI/ComponentsView.swift
Labels: fixed

#1209 COIOS-600: Fix failing tests on demo app
  Demo/SwiftUI/ComponentsView.swift
  Scripts/test-carthage-integration.sh
  Tests/AdyenSwiftUI Tests/AdyenSwiftUITests.swift
  Tests/Card Tests/CardComponentTests.swift
Labels: chore

#1210 Fix carthage github action
  Scripts/test-carthage-integration.sh
Labels: chore

#1202 Allow multi line for text field's alert
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
Labels: fixed

#1217 COIOS-603: ACH component improvements
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  AdyenDropIn/Models/DropInConfiguration.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/DropIn Tests/ComponentManagerTests.swift
Labels: new

#1221 chore: Using default header comment on new files
  Adyen.xcodeproj/xcshareddata/IDETemplateMacros.plist
Labels: chore

#1224 Bug template update
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#1203 Allow gift card component to visualize more than 20 digits
  AdyenCard/Formatters/CardNumberFormatter.swift
  Tests/Components Tests/Gift Card/GiftCardComponentTests.swift
Labels: fixed
