Repository Adyen/adyen-ios, pull requests merged in 2023-12, with the labels that each got.

#1480 `chore` Converting platform to enum
  Adyen/Analytics/Models/TelemetryData.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
Labels: chore

#1482 `improvement` Enable library evolution
  .github/workflows/test_library_evolution.yml
  Adyen/Core/APIClient/APIContext.swift
  Adyen/Core/Core Protocols/Details.swift
  Adyen/Core/Core Protocols/PaymentMethod.swift
  Tests/Adyen Tests/Core/PaymentMethodTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/DropIn Tests/ComponentManagerTests.swift
Labels: improvement

#1489 Update didComplete signature
  README.md
Labels: chore

#1499 `bugfix` Submit action is still disabled after CVC is filled
  AdyenCard/Components/Stored Card/StoredCardAlertManager.swift
  AdyenCard/Formatters/CardSecurityCodeFormatter.swift
  AdyenCard/Validators/CardSecurityCodeValidator.swift
  Tests/Card Tests/StoredCardComponentTests.swift
Labels: fixed
