Repository Adyen/adyen-ios, pull requests merged in 2023-09, with the labels that each got.

#1349 Update format_project.yml
  .github/workflows/format_project.yml
Labels: chore

#1369 Improvement: Added disabling stored payment method feature for DropIn session flow
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
Labels: improvement

#1368 change: v5 Xcode 15 fixes
  Adyen.docc/Installation.md
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Adyen/Utilities/AdyenCoder.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/Components/3DS2/ThreeDSResult.swift
  AdyenEncryption/JOSE/Encryption Algorithms/JSON Web Encryption/JSONWebEncryption.swift
  AdyenEncryption/JOSE/Encryption Algorithms/JSON Web Encryption/JSONWebEncryptionGenerator.swift
  AdyenEncryption/Payload/Payload.swift
  Package.swift
  README.md
  Scripts/test-CocoaPods-integration.sh
  Scripts/test-SPM-integration.sh
  Tests/Actions Tests/Voucher/BoletoVoucherShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/DokuVoucherUITests.swift
  Tests/Actions Tests/Voucher/EContextATMShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/EContextStoresVoucherViewControllerProviderTests.swift
  Tests/Actions Tests/Voucher/MultibancoShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/OXXOShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/VoucherComponentTests.swift
  Tests/Adyen Tests/Core/PaymentMethodTests.swift
  Tests/Adyen Tests/Utilities/AdyenCoderTests.swift
  Tests/Adyen Tests/Utilities/AmountFormatterTests.swift
  Tests/Adyen Tests/Utilities/LogoGeneratorTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
  Tests/Card Tests/BCMCComponentTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Card Tests/StoredCardAlertManagerTests.swift
  Tests/Card Tests/Utilities/CardEncryptorCardTests.swift
  Tests/Components Tests/Apple Pay/ApplePayDetailsTest.swift
  Tests/Components Tests/IssuerList/IssuerListComponentTests.swift
  Tests/Components Tests/Online Banking/OnlineBankingComponentTests.swift
  Tests/Components Tests/UPIComponent/UPIComponentTests.swift
  Tests/DropIn Tests/ComponentManagerTests.swift
  Tests/DropIn Tests/PreselectedPaymentComponentTests.swift
  Tests/Helpers/XCTestCase+Available.swift
  Tests/Helpers/XCTestCase+Coder.swift
  Tests/Session Tests/SessionTests.swift
  UITests/Components/IssuerList/IssuerListComponentUITests.swift
  UITests/Components/Online Banking/OnlineBankingComponentUITests.swift
Labels: changed

#1381 chore: update V4 format script
  .github/workflows/format_project.yml
Labels: chore

#1373 Update 3ds2sdk version to 2.3.3
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprintToken.swift
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
  Scripts/generate_docc_documentation.sh
  Tests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: chore

#1390 Fix error message on ApplePayComponent Example
  Demo/Common/IntegrationExamples/Components/ApplePayComponentExample.swift
Labels: chore

#1389 chore: Prevent palApiClient from releasing
  Demo/Common/Helpers/APIClientHelper.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataAdvancedFlowProtocol.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
Labels: chore

#1325 fix: Improve FullScreenViewController compatibility with AlertViewController
  AdyenSwiftUI/Present View Controller/FullScreenViewControllerPresenter.swift
Labels: fixed

#1392 Fix `didCancel` call on DropIn [no tests]
  AdyenDropIn/DropInComponent.swift
Labels: fixed

#1393 chore: simplify DropIn Advanced Example
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
Labels: chore

#1400 chore: update doc links to 5.4.0
  README.md
Labels: chore

#1401 improvement: Updating github docs version on increment script
  Scripts/increment_version.sh
Labels: chore
