Repository Adyen/adyen-ios, pull requests merged in 2023-11, with the labels that each got.

#1428 Update Carthage resolve
  Cartfile.resolved
Labels: chore

#1407 chore: Added 2-step address lookup
  Adyen.docc/AddressLookup.md
  Adyen.docc/Components.md
  Adyen.docc/DropIn.md
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/View Controllers/AddressLookup/AddressLookupProvider.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupViewController+ViewModel.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupViewController.swift
  Adyen/UI/View Controllers/AddressLookup/Search/AddressLookupSearchViewController+ViewModel.swift
  Adyen/UI/View Controllers/AddressLookup/Search/AddressLookupSearchViewController.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentConfiguration.swift
  AdyenCard/Components/Card/CardViewController.swift
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/IntegrationExamples/DemoAddressLookupProvider.swift
  Demo/Common/IntegrationExamples/MapkitAddressLookupProvider.swift
  Demo/Configuration.swift
  Tests/Adyen Tests/Mocks/MockAddressLookupProvider.swift
  Tests/Adyen Tests/UI/View Controllers/AddressLookupViewControllerTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/DummyData/DummyPaymentMethods.swift
  spell-check-excluded-files-list
  spell-check-word-allow-list.yaml
Labels: changed

#1433 chore: Updating api version to 71
  Demo/Configuration.swift
Labels: chore

#1448 Disable Bizum PM
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Tests/Adyen Tests/Core/PaymentMethodTests.swift
  Tests/DummyData/DummyPaymentMethods.swift
  spell-check-word-allow-list.yaml
Labels: fixed

#1446 fix: Correctly read potential localization overrides from the main bundle
  Adyen/Utilities/Localization.swift
Labels: fixed

#1443 chore: Reusing encoded header to prevent signature mismatch
  AdyenEncryption/JOSE/Encryption Algorithms/JSON Web Encryption/JSONWebEncryption.swift
  AdyenEncryption/JOSE/Encryption Algorithms/JSON Web Encryption/JSONWebEncryptionGenerator.swift
Labels: chore

#1455 `chore` Fix build.yml
  .github/workflows/build.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIKitTests.xcscheme
  Tests/Actions Tests/Redirect/RedirectComponentTests.swift
  Tests/Adyen Tests/Utilities/AmountFormatterTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Components Tests/Apple Pay/ApplePayComponentTests.swift
  Tests/Components Tests/Apple Pay/PreApplePayComponentTests.swift
  Tests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/DropIn Tests/ComponentManagerTests.swift
  Tests/DropIn Tests/ModalToolbarTests.swift
  Tests/Helpers/XCTestCase+Available.swift
  UITests/Components/BLIK/BLIKComponentUITests.swift
Labels: chore

#1458 `chore` Fix `keyWindow` warnings
  Adyen/UI/List/ListItem.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  Demo/Common/Helpers/APIClientHelper.swift
  Demo/Common/Networking/PaymentsRequest.swift
  Tests/Actions Tests/ActionComponent/AdyenActionComponentTests.swift
  Tests/Actions Tests/Await/AwaitComponentTests.swift
  Tests/Actions Tests/Redirect/RedirectComponentTests.swift
  Tests/Actions Tests/Voucher/BoletoVoucherShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/DokuVoucherUITests.swift
  Tests/Actions Tests/Voucher/EContextATMShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/EContextStoresVoucherViewControllerProviderTests.swift
  Tests/Actions Tests/Voucher/MultibancoShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/OXXOShareableVoucherViewProviderTests.swift
  Tests/Actions Tests/Voucher/VoucherComponentTests.swift
  Tests/Adyen Tests/UI/Form/FormItems/Error Item/FormErrorItemTests.swift
  Tests/Adyen Tests/UI/Form/FormItems/Picker/FormPickerItemTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressInputFormViewControllerTests.swift
  Tests/Adyen Tests/UI/View Controllers/FormPickerSearchViewControllerTests.swift
  Tests/Adyen Tests/UI/View Controllers/SearchViewControllerTests.swift
  Tests/Adyen Tests/UI/Views/LoadingViewTests.swift
  Tests/Card Tests/BCMCComponentTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Card Tests/StoredCardAlertManagerTests.swift
  Tests/Card Tests/StoredCardComponentTests.swift
  Tests/Card Tests/StoredPaymentMethodComponentTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/Components Tests/Affirm/AffirmComponentTests.swift
  Tests/Components Tests/Apple Pay/PreApplePayComponentTests.swift
  Tests/Components Tests/BACS Direct Debit/BACSDirectDebitComponentTests.swift
  Tests/Components Tests/BACS Direct Debit/DocumentComponentTests.swift
  Tests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/Components Tests/Boleto/BoletoComponentTests.swift
  Tests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/Components Tests/Doku/DokuComponentTests.swift
  Tests/Components Tests/Gift Card/GiftCardComponentTests.swift
  Tests/Components Tests/IssuerList/IssuerListComponentTests.swift
  Tests/Components Tests/MB Way/MBWayComponentTests.swift
  Tests/Components Tests/QRCode/QRCodeActionComponentTests.swift
  Tests/Components Tests/Qiwi Wallet/QiwiWalletComponentTests.swift
  Tests/Components Tests/SEPA Tests/SEPADirectDebitComponentTests.swift
  Tests/Components Tests/Seven Eleven Component/BasicPersonalInfoFormComponentTests.swift
  Tests/DropIn Tests/DropInActionTests.swift
  Tests/DropIn Tests/DropInTestInternal.swift
  Tests/DropIn Tests/DropInTests.swift
  Tests/DropIn Tests/ModalViewControllerTests.swift
  Tests/DropIn Tests/Payment Method List/PaymentMethodListComponentTests.swift
  Tests/DropIn Tests/PreselectedPaymentComponentTests.swift
  Tests/Helpers/UIViewController+Search.swift
  Tests/Helpers/XCTestCase+RootViewController.swift
  Tests/Session Tests/SessionTests.swift
  UITests/Components/Atome/AtomeComponentUITests.swift
Labels: chore

#1460 `chore` Fix boleto tests
  UITests/Components/Boleto/BoletoComponentUITests.swift
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testPaymentDataNoName-iPhone12.boleto_flow_no_name.png
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testPaymentDataProvided-iPhone12.boleto_flow.png
Labels: chore

#1308 Delegated authentication - Delete API Integration
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDAScreenPresenter.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprint.swift
  AdyenActions/Components/3DS2/ThreeDSResult.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: chore

#1456 chore: Adding optional AdyenDelegatedAuthentication target
  .gitignore
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenDelegatedAuthentication.xcscheme
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenDelegatedAuthentication/AdyenDelegatedAuthentication.h
  AdyenDelegatedAuthentication/AdyenDelegatedAuthentication.swift
  Cartfile
  Cartfile.resolved
  Package.swift
  Scripts/test-CocoaPods-integration.sh
  Scripts/test-SPM-integration.sh
  Scripts/test-carthage-integration.sh
  Tests/Card Tests/3DS2 Component/AuthenticationServiceMock.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: chore

#1431 fix: Prefil phone number doesn't change countryCode
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Components/AbstractPersonalInformationComponent/PhoneFormItemInjector.swift
  Adyen/Model/PrefilledShopperInformation.swift
  Adyen/UI/Form/Items/Phone Number/FormPhoneNumberItem.swift
  Adyen/UI/Form/Items/Value Pickers/Phone Extension Picker/FormPhoneExtensionPickerItem.swift
  AdyenComponents/Affirm/AffirmComponent.swift
  AdyenComponents/Atome/AtomeComponent.swift
  MIGRATION.md
  Tests/Card Tests/Items/CardNumberItem/FormItemViewBuilderTests.swift
  Tests/Components Tests/Affirm/AffirmComponentTests.swift
  Tests/Components Tests/Atome/AtomeComponentTests.swift
  UITests/Components/Affirm/AffirmComponentUITests.swift
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsNotSet-iPhone12.shopper-info-prefilled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsSet-iPhone12.shopper-info-prefilled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.shopper-info-prefilled.png
  UITests/Components/Atome/AtomeComponentUITests.swift
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAllRequiredTextField_shouldExist-iPhone12.all_required_fields_exist.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.prefilled_shopper_info.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
  spell-check-word-allow-list.yaml
Labels: fixed

#1469 `chore` Removing unneeded availability checks
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/View Controllers/SecuredViewController.swift
  AdyenComponents/Apple Pay/ApplePayConfiguration.swift
  AdyenDropIn/Views/PreApplePayView.swift
  Demo/UIKit/ComponentsView.swift
  Tests/Adyen Tests/Utilities/AmountFormatterTests.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
  Tests/Components Tests/Apple Pay/ApplePayComponentTests.swift
  Tests/Helpers/XCTestCase+Available.swift
Labels: chore

#1468 `chore` Fix all warnings
  .swiftlint.yml
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Core Protocols/Component.swift
  Adyen/Core/Core Protocols/PaymentAwareComponent.swift
  Adyen/Core/Models/CardType.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Adyen/Helpers/UIViewAnimation.swift
  Adyen/UI/Form/Items/Phone Number/FormPhoneNumberItem.swift
  Adyen/UI/List/ListItem.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupViewController.swift
  Adyen/Utilities/External/AllCountriesPhoneExtensions.swift
  Adyen/Utilities/Observable/AdyenObserver.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenDropIn/Utilities/ComponentManager.swift
  AdyenWeChatPay/WeChatPayActionComponent/WeChatPayActionComponent.swift
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/IntegrationExamples/Components/InstantPaymentComponentAdvancedFlowExample.swift
  Demo/Configuration.swift
  Demo/SwiftUI/ComponentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
  Tests/Actions Tests/ActionComponent/AdyenActionComponentTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/Components Tests/Affirm/AffirmComponentTests.swift
  Tests/Components Tests/Doku/DokuComponentTests.swift
  Tests/Components Tests/MB Way/MBWayComponentTests.swift
  Tests/Components Tests/Seven Eleven Component/BasicPersonalInfoFormComponentTests.swift
  Tests/DropIn Tests/ComponentManagerTests.swift
  Tests/DummyData/Dummy.swift
  UITests/Components/Boleto/BoletoComponentUITests.swift
Labels: chore

#1473 `chore` Adding internal telemetry context (configuration)
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/AnalyticsProvider/TelemetryTracker.swift
  Adyen/Analytics/Models/TelemetryData.swift
  Adyen/Analytics/Requests/TelemetryRequest.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
Labels: chore
