Repository Adyen/adyen-ios, pull requests merged in 2023-01, with the labels that each got.

#1111 v4: Fix Apple pay
  Adyen.xcodeproj/project.pbxproj
  AdyenComponents/Apple Pay/ApplePayComponentExtensions.swift
  AdyenDropIn/Components/PreApplePayComponent.swift
  AdyenDropIn/DropInComponentExtensions.swift
  AdyenDropIn/Presentation/NavigationDelegate.swift
  Tests/AdyenTests/Adyen Tests/Components/Apple Pay/ApplePayComponentTests.swift
  Tests/AdyenTests/Adyen Tests/Components/Apple Pay/PreApplePayComponentTests.swift
  Tests/AdyenTests/Adyen Tests/Components/PresentationDelegateMock.swift
Labels: fixed

#1107 Update docs and README
  Adyen.docc/Components.md
  Adyen.docc/DropIn.md
  Adyen.docc/ThreeAPIs.md
  README.md
Labels: chore

#1116 Make Demo app Configuration iOS 16 friendly
  Demo/Common/Configuration/ConfigurationView.swift
Labels: chore

#1123 chore: update references for OnlineBanking
  README.md
Labels: chore

#1118 covered IssuerListComponent with snap shot tests
  .github/workflows/pr_scan.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHostUITests.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIKitTests.xcscheme
  Demo/Configuration.swift
  Tests/Adyen Tests/Core/PaymentMethodTests.swift
  Tests/Adyen Tests/UI/List Component/ListViewControllerTests.swift
  Tests/Components Tests/IssuerList/IssuerListComponentTests.swift
  Tests/DummyData/DummyPaymentMethods.swift
  UITests/Components/Affirm/AffirmComponentUITests.swift
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsNotSet-iPhone12.shopper-info-prefilled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsSet-iPhone12.shopper-info-prefilled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirm_givenNoShopperInformation_shouldNotPrefill-iPhone12.shopper-info-not-filled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.shopper-info-prefilled.png
  UITests/Components/Atome/AtomeComponentUITests.swift
  UITests/Components/IssuerList/IssuerListComponentUITests.swift
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.initial_state.txt
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.loading_first_cell.txt
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.stopped_loading.txt
  UITests/Components/Online Banking/OnlineBankingComponentUITests.swift
  UITests/Helpers/XCTestCase+SnapshotTesting.swift
  UITests/UI/ListViewControllerUITests.swift
  UITests/UI/__Snapshots__/ListViewControllerUITests/testUIConfiguration-iPhone12.listViewController_UI_Configuration.png
Labels: chore

#1125 Covered QRCodeActionComponent with snapshot UI tests
  AdyenActions/Components/QRCode/QRCodeActionComponent.swift
  UITests/Components/QRCode/QRCodeActionComponentUITests.swift
  UITests/Components/QRCode/__Snapshots__/QRCodeActionComponentUITests/testUIConfigurationForPix-iPhone12.pix.png
  UITests/Components/QRCode/__Snapshots__/QRCodeActionComponentUITests/testUIConfigurationForPromptPay-iPhone12.promptPay.png
Labels: chore

#1128 Update README
  README.md
Labels: chore

#1127 Xcode warnings
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/Adyen.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenActions.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenCard.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenComponents.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenDropIn.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenEncryption.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenSession.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenSwiftUI.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenSwiftUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenSwiftUITests.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHostUITests.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIKitTests.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenWeChatPay.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/Localization.xcscheme
Labels: chore

#1124 Covered AtomeComponent with snapshot tests
  UITests/Components/Atome/AtomeComponentUITests.swift
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAllRequiredTextField_shouldExist-iPhone12.all_required_fields_exist.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAtome_givenNoShopperInformation_shouldNotPrefill-iPhone12.empty_form.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.prefilled_shopper_info.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
Labels: chore

#1133 Demo PR for the presentation (please don't code review)
  Adyen.xcodeproj/project.pbxproj
Labels: new, chore
