Repository Adyen/adyen-ios, pull requests merged in 2023-10, with the labels that each got.

#1402 improvement: Add cashapp toggle in demo settings
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/Configuration/DropInSettingsView.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/Networking/SessionRequest.swift
  Demo/Configuration.swift
Labels: chore, improvement

#1403 fix: Creating valid build for testflight
  Adyen.xcodeproj/project.pbxproj
  Demo/UIKit/Info.plist
Labels: chore

#1399 chore: 🤖 Switching to macos-13-xl runner using Xcode 14.3
  .github/workflows/pr_scan.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHostUITests.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIKitTests.xcscheme
  Adyen/UI/Form/Items/Button/FormButtonItemView.swift
  AdyenActions/UI/View Controllers/QR Code/QRCodeView.swift
  AdyenActions/UI/View Controllers/Voucher/VoucherView.swift
  Scripts/test-carthage-integration.sh
  Tests/Actions Tests/Voucher/VoucherViewTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressInputFormViewControllerTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/Components Tests/BACS Direct Debit/DocumentComponentTests.swift
  Tests/Helpers/UIView+Search.swift
  Tests/Helpers/UIViewController+Search.swift
  Tests/Helpers/XCTestCase+RootViewController.swift
  Tests/Helpers/XCTestCase+Wait.swift
  Tests/Helpers/XCTestCaseExtension.swift
  Tests/Helpers/XCTestCaseExtensions.swift
  UITests/Components/Affirm/AffirmComponentUITests.swift
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsNotSet-iPhone12.shopper-info-prefilled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsSet-iPhone12.shopper-info-prefilled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirm_givenNoShopperInformation_shouldNotPrefill-iPhone12.shopper-info-not-filled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.shopper-info-prefilled.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAllRequiredTextField_shouldExist-iPhone12.all_required_fields_exist.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAtome_givenNoShopperInformation_shouldNotPrefill-iPhone12.empty_form.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.prefilled_shopper_info.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
  UITests/Components/BLIK/BLIKComponentUITests.swift
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testSubmitButtonLoading-iPhone12.initial_state.png
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testSubmitButtonLoading-iPhone12.stopped_loading.png
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testSubmitForm-iPhone12.blik_flow.png
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testPaymentDataProvided-iPhone12.boleto_flow.png
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testPaymentDataProvidedNoEmail-iPhone12.boleto_flow.png
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
  UITests/Components/Doku/__Snapshots__/DokuComponentUITests/testSubmitForm-iPhone12.doku_flow.png
  UITests/Components/Doku/__Snapshots__/DokuComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.initial_state.png
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.loading_first_cell.png
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.stopped_loading.png
  UITests/Components/MBWay/__Snapshots__/MBWayComponentUITests/testSubmitForm-iPhone12.mbway_flow.png
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testPressContinueButton-iPhone12.online_banking_flow.png
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testUIElements-iPhone12.UI_configuration.png
  UITests/Components/QRCode/QRCodeActionComponentUITests.swift
  UITests/Components/UPIComponent/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPhone12.prefilled_vpa.png
  UITests/Helpers/XCTestCase+SnapshotTesting.swift
  UITests/UI/__Snapshots__/ListViewControllerUITests/testUIConfiguration-iPhone12.listViewController_UI_Configuration.png
Labels: chore

#1411 CI: Run PR scanner on `develop`
  .github/workflows/pr_scan.yml
Labels: chore

#1410 chore: Adding tests for didCancel [INJECTED]
  Adyen.xcodeproj/project.pbxproj
  Adyen/Helpers/AdyenDependencies.swift
  AdyenActions/Components/Redirect/BrowserComponent.swift
  AdyenActions/Components/Redirect/OpenExternalAppDetector+DependencyKey.swift
  AdyenActions/Components/Redirect/OpenExternalAppDetector.swift
  Scripts/test-carthage-integration.sh
  Tests/Card Tests/Mocks/OpenExternalAppDetector+Mock.swift
  Tests/DropIn Tests/DropInTests.swift
  Tests/DummyData/Dummy.swift
Labels: chore

#1412 Update README.md with Sonar coverage
  README.md
Labels: chore

#1408 fix: Apple pay sheet dismissal issue
  Adyen.xcodeproj/project.pbxproj
  Adyen/Helpers/AdyenDependencies.swift
  AdyenActions/Components/Redirect/BrowserComponent.swift
  AdyenActions/Components/Redirect/OpenExternalAppDetector+DependencyKey.swift
  AdyenActions/Components/Redirect/OpenExternalAppDetector.swift
  AdyenDropIn/DropInComponent.swift
  Scripts/test-carthage-integration.sh
  Tests/Card Tests/Mocks/OpenExternalAppDetector+Mock.swift
  Tests/DropIn Tests/DropInTests.swift
  Tests/DummyData/Dummy.swift
Labels: fixed

#1406 chore: ListItem triggered loading state
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHostUITests.xcscheme
  Adyen/UI/List/ListItem.swift
  Adyen/UI/List/ListViewController.swift
  Adyen/UI/View Controllers/SearchViewController/SearchViewController+ViewModel.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenDropIn/Components/PaymentMethodListComponent.swift
  Demo/Configuration.swift
  Tests/Card Tests/CardComponentTests.swift
  UITests/Components/BLIK/BLIKComponentUITests.swift
  UITests/Components/IssuerList/IssuerListComponentUITests.swift
Labels: chore

#1417 improvement: Adding documentation for custom display information
  .github/workflows/regenerate-docs.yml
  Adyen.docc/API Reference.md
  Adyen.docc/AdvancedFlow.md
  Adyen.docc/Adyen.md
  Adyen.docc/Components.md
  Adyen.docc/Contributing.md
  Adyen.docc/Customization.md
  Adyen.docc/DropIn.md
  Adyen.docc/Localization.md
  Adyen.docc/Support.md
  Scripts/generate_docc_documentation.sh
Labels: improvement

#1421 improvements: Docc + Readme
  Adyen.docc/AdvancedFlow.md
  Adyen.docc/Contributing.md
  Adyen.docc/Installation.md
  README.md
Labels: improvement

#1419 Feature: Installment amount display
  Adyen/Core/Components/Installment/InstallmentOptions.swift
  AdyenCard/Form/Installments/FormCardInstallmentsItem.swift
  AdyenSession/API/Session Setup/SessionSetupRequest.swift
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/Networking/SessionRequest.swift
  Demo/Configuration.swift
  Tests/Card Tests/CardComponentTests.swift
Labels: new

#1414 improvement: Partial payment accessibility
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/ar.lproj/Localizable.strings
  Adyen/Assets/cs-CZ.lproj/Localizable.strings
  Adyen/Assets/da-DK.lproj/Localizable.strings
  Adyen/Assets/de-DE.lproj/Localizable.strings
  Adyen/Assets/el-GR.lproj/Localizable.strings
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Assets/es-ES.lproj/Localizable.strings
  Adyen/Assets/fi.lproj/Localizable.strings
  Adyen/Assets/fr-FR.lproj/Localizable.strings
  Adyen/Assets/hr-HR.lproj/Localizable.strings
  Adyen/Assets/hu-HU.lproj/Localizable.strings
  Adyen/Assets/it-IT.lproj/Localizable.strings
  Adyen/Assets/ja-JP.lproj/Localizable.strings
  Adyen/Assets/ko.lproj/Localizable.strings
  Adyen/Assets/nb-NO.lproj/Localizable.strings
  Adyen/Assets/nl-NL.lproj/Localizable.strings
  Adyen/Assets/pl-PL.lproj/Localizable.strings
  Adyen/Assets/pt-BR.lproj/Localizable.strings
  Adyen/Assets/pt-PT.lproj/Localizable.strings
  Adyen/Assets/ro-RO.lproj/Localizable.strings
  Adyen/Assets/ru-RU.lproj/Localizable.strings
  Adyen/Assets/sk-SK.lproj/Localizable.strings
  Adyen/Assets/sl-SI.lproj/Localizable.strings
  Adyen/Assets/sv-SE.lproj/Localizable.strings
  Adyen/Assets/zh-CN.lproj/Localizable.strings
  Adyen/Assets/zh-TW.lproj/Localizable.strings
  Adyen/Core/APIClient/Responses/OrderStatusResponse.swift
  Adyen/Core/Models/CardType.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Adyen/UI/List/ListFooterView.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenCard/Components/GiftCardComponent/GiftCardConfirmationPaymentMethod.swift
  AdyenDropIn/Utilities/ComponentManager.swift
  Tests/Adyen Tests/Core/PaymentMethodTests.swift
  UITests/Components/Affirm/AffirmComponentUITests.swift
  UITests/UI/__Snapshots__/ListViewControllerUITests/testUIConfiguration-iPhone12.listViewController_UI_Configuration.png
Labels: improvement

#1429 Create codeql.yml
  .github/workflows/codeql.yml
Labels: chore, improvement
