Repository Adyen/adyen-ios, pull requests merged in 2023-02, with the labels that each got.

#1131 Adding cancel polling component
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/ToolBar/CancellableToolBar.swift
  Adyen/Core/ToolBar/ModalToolbar.swift
  AdyenActions/Components/QRCode/QRCodeActionComponent.swift
  AdyenDropIn/Presentation/ModalViewController.swift
  UITests/Components/QRCode/QRCodeActionComponentUITests.swift
  UITests/Components/QRCode/__Snapshots__/QRCodeActionComponentUITests/testQRCodeCancelButtonOnUPI-iPhone12.upi_cancel_button.png
Labels: new

#1135 chore: remove carthage script
  Scripts/test-carthage-integration.sh
Labels: chore

#1136 Keep "loaded state" when payment list skipped
  AdyenDropIn/DropInComponent.swift
Labels: fixed

#1138 Added docs for new components
  Adyen.docc/API Reference.md
  Adyen.docc/Components.md
  README.md
Labels: chore

#1140 Docc script: Fix PIF cache issue on SPM
  Scripts/generate_docc_documentation.sh
Labels: chore

#1142 chore: revert apple pay recurring for now
  AdyenComponents/Apple Pay/ApplePayComponent.swift
  Tests/Components Tests/Apple Pay/ApplePayComponentTests.swift
Labels: chore

#1143 fix: returning 8 digit pan when bin length is >= 16
  AdyenCard/Form/FormCardNumberItem.swift
  Tests/Card Tests/BCMCComponentTests.swift
  Tests/Card Tests/CardComponentTests.swift
Labels: fixed

#1141 chore: update version to 5.1.0
  Adyen.xcodeproj/project.pbxproj
  Adyen/Info.plist
  AdyenActions/Info.plist
  AdyenCard/Info.plist
  AdyenComponents/Info.plist
  AdyenDropIn/Info.plist
  AdyenEncryption/Info.plist
  AdyenSwiftUI/Info.plist
  AdyenWeChatPay/Info.plist
  Demo/SwiftUI/Info.plist
  Demo/UIKit/Info.plist
  Tests/AdyenSwiftUI Tests/Info.plist
  Tests/Info.plist
Labels: chore

#1145 Format project
  Adyen/Core/ToolBar/CancellableToolBar.swift
  Adyen/UI/Form/Items/Address/AddressViewModel.swift
  Adyen/UI/Form/Items/FormImageItem/FormImageItem.swift
  Adyen/UI/Styles/FormComponentStyle.swift
  Adyen/UI/View Controllers/SearchViewController.swift
  AdyenActions/UI/View Controllers/Await/AwaitComponentViewModel.swift
  AdyenCard/Validators/AddressValidator.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenComponents/UPI/UPIComponent.swift
  AdyenDropIn/Presentation/ModalViewController.swift
  Tests/Card Tests/Validators/EmailValidatorTests.swift
  Tests/Components Tests/QRCode/QRCodeActionComponentTests.swift
  UITests/Components/Affirm/AffirmComponentUITests.swift
  UITests/Components/Atome/AtomeComponentUITests.swift
  UITests/Components/QRCode/QRCodeActionComponentUITests.swift
  UITests/Components/UPIComponent/UPIComponentUITests.swift
  UITests/Helpers/XCTestCase+SnapshotTesting.swift
Labels: chore

#1147 Patch docs script
  Scripts/generate_docc_documentation.sh
Labels: chore

#1146 Added snapshots tests for Online Banking component.
  UITests/Components/Online Banking/OnlineBankingComponentUITests.swift
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testContinueButtonLoading-iPhone12.initial_state.txt
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testContinueButtonLoading-iPhone12.stopped_loading.txt
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testPressContinueButton-iPhone12.online_banking_flow.png
  UITests/Components/Online Banking/__Snapshots__/OnlineBankingComponentUITests/testUIElements-iPhone12.UI_configuration.png
Labels: chore

#1149 Update generate_docc_documentation.sh
  Scripts/generate_docc_documentation.sh
Labels: chore

#1151 Fixed the publish-demo-app.yml github workflow
  .github/workflows/publish-demo-app.yml
  Adyen.xcodeproj/project.pbxproj
Labels: chore

#1152 chore: update podspec
  Adyen.podspec
Labels: chore

#1153 Added snapshot tests for BLIK component
  Adyen.xcodeproj/project.pbxproj
  Tests/Components Tests/BLIK Component/BLIKComponentTests.swift
  UITests/Components/BLIK/BLIKComponentUITests.swift
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testSubmitButtonLoading-iPhone12.initial_state.txt
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testSubmitButtonLoading-iPhone12.stopped_loading.txt
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testSubmitForm-iPhone12.blik_flow.png
  UITests/Components/BLIK/__Snapshots__/BLIKComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
Labels: chore

#1155 Added snapshot tests for MBWay component
  Adyen.xcodeproj/project.pbxproj
  Tests/Components Tests/MB Way/MBWayComponentTests.swift
  UITests/Components/MBWay/MBWayComponentUITests.swift
  UITests/Components/MBWay/__Snapshots__/MBWayComponentUITests/testSubmitForm-iPhone12.mbway_flow.png
  UITests/Components/MBWay/__Snapshots__/MBWayComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
Labels: chore

#1157 Fix unit tests and carthage tests
  Adyen.xcodeproj/project.pbxproj
  Tests/Card Tests/3DS2 Component/AuthenticationServiceMock.swift
Labels: chore

#1156 Added snapshot testing for boleto component
  Adyen.xcodeproj/project.pbxproj
  Tests/Components Tests/Boleto/BoletoComponentTests.swift
  Tests/DummyData/Dummy.swift
  UITests/Components/Boleto/BoletoComponentUITests.swift
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testPaymentDataProvided-iPhone12.boleto_flow.png
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testPaymentDataProvidedNoEmail-iPhone12.boleto_flow.png
  UITests/Components/Boleto/__Snapshots__/BoletoComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
Labels: chore

#1162 Fixed search bar background color issue in dark mode
  Adyen/UI/View Controllers/SearchViewController.swift
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.initial_state.txt
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.loading_first_cell.txt
  UITests/Components/IssuerList/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone12.stopped_loading.txt
Labels: fixed

#1165 Added snapshot tests for Doku component
  Adyen.xcodeproj/project.pbxproj
  Tests/Components Tests/Doku/DokuComponentTests.swift
  UITests/Components/Doku/DokuComponentUITests.swift
  UITests/Components/Doku/__Snapshots__/DokuComponentUITests/testSubmitForm-iPhone12.doku_flow.png
  UITests/Components/Doku/__Snapshots__/DokuComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
Labels: chore
