Repository Adyen/adyen-ios, pull requests merged in 2023-08, with the labels that each got.

#1293 chore: Added improve label in the validate PR label list
  .github/workflows/validate_pr_labels_and_release_notes.yml
Labels: chore

#1298 chore: Handle redirect on demo card component
  Demo/Common/IntegrationExamples/Components/CardComponentExample.swift
Labels: chore

#1297 change: replace session delegate with new sessionResult
  AdyenSession/AdyenSession+ActionComponentDelegate.swift
  AdyenSession/AdyenSession+PaymentComponentDelegate.swift
  AdyenSession/AdyenSessionDelegate.swift
Labels: chore

#1295 feature: Detached address input
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/Form/FormItemViewBuilder.swift
  Adyen/UI/Form/Items/Address/FormAddressItem+Configuration.swift
  Adyen/UI/Form/Items/Address/FormAddressItem.swift
  Adyen/UI/Form/Items/Address/Picker/FormAddressPickerItem.swift
  Adyen/UI/Form/Items/Address/Picker/FormAddressPickerItemView.swift
  Adyen/UI/Form/Items/Button/SearchButton/FormSearchButtonItem.swift
  Adyen/UI/Form/Items/Button/SearchButton/FormSearchButtonItemView.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupStyle.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupViewController+ViewModel.swift
  Adyen/UI/View Controllers/AddressLookup/AddressLookupViewController.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressInputFormViewController+ViewModel.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressInputFormViewController.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressLookupFormViewController.swift
  AdyenCard/Components/BCMC/BCMCComponent.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentConfiguration.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressItemTests.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressPickerItemTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressInputFormViewControllerTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressLookupViewControllerTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Card Tests/Items/CardNumberItem/FormItemViewBuilderTests.swift
  Tests/Helpers/UIBarButtonItem+XCTest.swift
Labels: new

#1294 feature: Added new initializer for Apple Pay configuration
  AdyenComponents/Apple Pay/ApplePayComponent.swift
  AdyenComponents/Apple Pay/ApplePayComponentError.swift
  AdyenComponents/Apple Pay/ApplePayConfiguration.swift
  AdyenComponents/Apple Pay/ApplePayPayment.swift
  Tests/Components Tests/Apple Pay/ApplePayComponentTests.swift
Labels: new

#1299 Add new locale instructions to Localization.md
  Adyen.docc/Localization.md
Labels: chore

#1301 chore: Separation of validation concerns
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  Adyen/UI/Form/Items/Value/FormValueItemView.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerItemView.swift
  Adyen/UI/Form/Items/Value/Selectable/FormSelectableValueItemView.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItemView.swift
Labels: chore

#1290 improvement: Card Component Accessibility
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Models/CardType.swift
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  Adyen/UI/Form/Items/Toggle/FormToggleItemView.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItemView.swift
  Adyen/UI/Views/UIView+Accessibility.swift
  AdyenCard/Form/FormCardLogosItemView.swift
  AdyenCard/Form/FormCardNumberItemView.swift
Labels: improvement

#1300 change: make countryCode optional for external session call
  AdyenSession/API/Session Setup/SessionSetupRequest.swift
  AdyenSession/AdyenSession.swift
Labels: changed

#1307 chore: Add AdyenCashAppPay to sonar-project.properties
  sonar-project.properties
Labels: chore

#1287 chore: Adding amount field to telemetry request
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/AnalyticsProvider/TelemetryTracker.swift
  Adyen/Analytics/Models/TelemetryData.swift
  Adyen/Analytics/Requests/TelemetryRequest.swift
  Adyen/Core/AdyenContext/AdyenContext.swift
  Demo/Common/Utils/APIClientMock.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderMock.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
  Tests/Adyen Tests/Core/AdyenContextTests.swift
  Tests/Card Tests/Utilities/CardBrandProviderTests.swift
  Tests/Session Tests/SessionTests.swift
Labels: chore

#1309 chore: Update 3ds2 version in docc script
  Scripts/generate_docc_documentation.sh
Labels: chore

#1315 release: Update documentation version
  README.md
Labels: chore

#1317 release: Updating migration guide
  Adyen.podspec
  MIGRATION.md
Labels: chore

#1319 Ci post release
  .github/workflows/post_release.yml
Labels: chore

#1322 chore: Fix generate_docc_documentation.sh
  Scripts/generate_docc_documentation.sh
Labels: chore

#1327 Fixed memory leak
  Adyen/UI/Form/Items/Value/FormValueItemView.swift
Labels: fixed

#1312 improvement: Added ApplePay settings for demo App
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/Configuration/ApplePaySettingsView.swift
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Configuration/ComponentsSettingsView.swift
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/Configuration/DropInSettingsView.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Configuration.swift
  spell-check-word-allow-list.yaml
Labels: improvement

#1304 new: Allow co-branded bcmc
  Adyen/Core/Payment Methods/BCMCPaymentMethod.swift
  Adyen/UI/Form/Items/Button/SearchButton/FormSearchButtonItemView.swift
  AdyenCard/Components/BCMC/BCMCComponent.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentConfiguration.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenCard/Form/FormCardNumberContainerItem.swift
  AdyenCard/Form/FormCardSecurityCodeItem.swift
  AdyenCard/Form/FormCardSecurityCodeItemView.swift
  AdyenCard/Utilities/BinLookup/BinLookupRequest.swift
  AdyenCard/Utilities/BinLookup/BinLookupService.swift
  AdyenCard/Utilities/CardType/BinInfoProvider.swift
  Tests/Card Tests/BCMCComponentTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Card Tests/Items/CardNumberItem/FormCardNumberItemTests.swift
  Tests/Card Tests/Utilities/CardBrandProviderTests.swift
Labels: new

#1330 new: v4 Allow co-branded bcmc
  Adyen/Core/Payment Methods/BCMCPaymentMethod.swift
  AdyenCard/Components/BCMC/BCMCComponent.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentConfiguration.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenCard/Form/FormCardNumberContainerItem.swift
  AdyenCard/Form/FormCardSecurityCodeItem.swift
  AdyenCard/Form/FormCardSecurityCodeItemView.swift
  AdyenCard/Utilities/BinLookup/BinLookupRequest.swift
  AdyenCard/Utilities/BinLookup/BinLookupService.swift
  AdyenCard/Utilities/CardType/BinInfoProvider.swift
  Tests/AdyenTests/Card Tests/BCMCComponentTests.swift
  Tests/AdyenTests/Card Tests/CardComponentTests.swift
  Tests/AdyenTests/Card Tests/Items/CardNumberItem/FormCardNumberItemTests.swift
  Tests/AdyenTests/Card Tests/Utilities/CardBrandProviderTests.swift
Labels: new

#1334 change: v4 Updated minor units for ISK and few other currencies
  Adyen/Formatters/AmountFormatter.swift
  Tests/AdyenTests/Adyen Tests/Utilities/AmountFormatterTests.swift
Labels: changed

#1333 change: ISK and few other currency minor units updates
  Adyen/Formatters/AmountFormatter.swift
  Demo/Configuration.swift
  Tests/Adyen Tests/Utilities/AmountFormatterTests.swift
Labels: changed

#1331 Fix leaks
  AdyenComponents/Issuer List/IssuerListComponent.swift
Labels: improvement

#1332 Added analytics settings
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Demo/Common/Configuration/AnalyticsSettingsView.swift
  Demo/Common/Configuration/ComponentsSettingsView.swift
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataAdvancedFlowProtocol.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
  Demo/Configuration.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
Labels: improvement

#1336 fix: Billing address title fix
  Adyen/UI/Form/Items/Address/FormAddressItem+Configuration.swift
  Adyen/UI/Form/Items/Address/FormAddressItem.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressInputFormViewController.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressItemTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressInputFormViewControllerTests.swift
  Tests/Card Tests/Items/CardNumberItem/FormItemViewBuilderTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/Components Tests/Boleto/BoletoComponentTests.swift
  UITests/Components/Affirm/AffirmComponentUITests.swift
  UITests/Components/Atome/AtomeComponentUITests.swift
Labels: fixed

#1339 chore: Improve increment version script
  Adyen.xcodeproj/project.pbxproj
  Scripts/increment_version.sh
Labels: chore
