Repository Adyen/adyen-ios, pull requests merged in 2023-04, with the labels that each got.

#1186 Add ability to filter ApplePay by funding source
  AdyenComponents/Apple Pay/ApplePayConfiguration.swift
Labels: new

#1184 Added Refactored DropIn with session flow for demo app
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/IntegrationExample.swift
  Demo/Common/IntegrationExampleComponents.swift
  Demo/Common/IntegrationExampleDropIn.swift
  Demo/Common/IntegrationExamplePartialPayment.swift
  Demo/Common/IntegrationExampleSession.swift
  Demo/Common/IntegrationExamples/DropIn.swift
  Demo/Common/IntegrationExamples/Protocols/DropInExampleProtocol.swift
  Demo/Common/IntegrationExamples/Protocols/PresenterExampleProtocol.swift
  Demo/SwiftUI/PaymentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
Labels: chore

#1190 Added Advanced flow in demo app
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/IntegrationExamples/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropInExample.swift
  Demo/Common/IntegrationExamples/Protocols/AdvancedFlowExampleProtocol.swift
  Demo/SwiftUI/PaymentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
Labels: chore

#1196 Update 3ds2sdk version to 2.3.1
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
Labels: changed

#1199 Refactoring of CardComponent for Demo app
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/IntegrationExamples/Components/CardComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataAdvancedFlowProtocol.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
  Demo/SwiftUI/PaymentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
Labels: chore
