Repository Adyen/adyen-ios, pull requests merged in 2024-12, with the labels that each got.

#1913 Allow setting `maxIssuerNumber` for Twint via Drop-In configuration
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/SDK/Twint+Injectable.swift
Labels: new

#1916 Twint crash fix
  AdyenActions/Components/SDK/Twint+Injectable.swift
  spell-check-word-allow-list.yaml
Labels: fixed

#1920 Fix card component stale state on dropin component reuse
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/Form/Items/Error/FormErrorItemView.swift
  AdyenCard/Form/DualBrandView.swift
  AdyenCard/Form/FormCardNumberItemView.swift
  Tests/IntegrationTests/Card Tests/DualBrandViewTests.swift
Labels: fixed

#1925 Run library-evolution workflow on macos-14-xlarge
  .github/workflows/test_library_evolution.yml
Labels: chore

#1918 Error events for 3ds2/redirect/encryption
  Adyen/Analytics/AnalyticsProvider/EventAnalyticsProvider.swift
  Adyen/Analytics/Models/AnalyticsConstants.swift
  Adyen/Analytics/Models/AnalyticsEventError.swift
  AdyenActions/Actions/RedirectAction.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2CompactActionHandler+Initializers.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2CompactActionHandler.swift
  AdyenActions/Components/3DS2/Fingerprint Submitter/ThreeDS2FingerprintSubmitter.swift
  AdyenActions/Components/Redirect/RedirectComponent.swift
  AdyenCard/Components/Card/CardComponentExtensions.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenCard/Components/Stored Card/StoredCardAlertManager.swift
  Tests/IntegrationTests/Actions Tests/Redirect/RedirectComponentTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/3DS2 Fingerprint Submitter/ThreeDS2FingerprintSubmitterTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
Labels: chore
