Repository Adyen/adyen-ios, pull requests merged in 2024-03, with the labels that each got.

#1532 [Twint] Checking for TwintSDK to make native and redirect flow possible
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  AdyenActions/Actions/SDKAction.swift
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  AdyenDropIn/DropInComponent.swift
Labels: chore

#1533 [Twint] Adding Configuration to provide return url for the TwintSDKAction
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
  Demo/SwiftUI/Info.plist
  Demo/UIKit/Info.plist
Labels: chore

#1534 [Twint] Alert presentation fix
  Adyen/Core/Components/Base/PresentableComponentWrapper.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
Labels: chore

#1535 Fixed DropIn Configuration for Twint
  AdyenDropIn/DropInComponent.swift
  AdyenDropIn/Models/DropInConfiguration.swift
  Demo/Configuration.swift
Labels: chore

#1536 Injecting Twint into the TwintSDKActionComponent
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Actions/TwintSDKAction.swift
  AdyenActions/Actions/TwintSDKData.swift
  AdyenActions/Components/SDK/TwintConforming.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
Labels: chore

#1537 Adding unit tests for the twint sdk action
  Adyen.xcodeproj/project.pbxproj
  Tests/Actions Tests/ActionComponent/TwintSDKActionTests.swift
Labels: chore

#1538 Moving TwintSpy to Test target
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/SDK/Twint+Injectable.swift
  Tests/Actions Tests/ActionComponent/Twint/Twint+Spy.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
Labels: chore

#1539 Improving drop-in test speed
  Tests/DropIn Tests/DropInActionTests.swift
  Tests/DropIn Tests/DropInTestInternal.swift
Labels: chore

#1540 handling twint redirect
  AdyenActions/Components/SDK/Twint+Injectable.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  Demo/UIKit/AppDelegate.swift
  Tests/Actions Tests/ActionComponent/Twint/Twint+Spy.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
Labels: chore

#1542 🚧 [WIP] Provide human-friendly error on PublicKeyProvider
  Adyen/Utilities/PublicKeyProvider/PublicKeyProvider.swift
Labels: fixed

#1544 Twint action full test
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/ToolBar/CancellableToolBar.swift
  AdyenActions/Actions/SDKAction.swift
  AdyenActions/Actions/TwintSDKAction.swift
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  AdyenDropIn/DropInComponent.swift
  AdyenDropIn/Models/DropInConfiguration.swift
  Demo/UIKit/AppDelegate.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Convenience.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Flows.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
  Tests/Helpers/ErrorMock.swift
Labels: chore

#1548 added documentation
  AdyenTwint/AdyenTwint.docc/AdyenTwint.md
  README.md
Labels: chore

#1546 Dev 64080: Revisit public interface of delegate authentication flow
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/3DS2/ThreeDS2Component.swift
  Tests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
Labels: feature request, chore

#1550 Adding AdyenAction tests for Twint
  AdyenTwint/TwintComponent.swift
  Tests/Actions Tests/ActionComponent/AdyenActionComponentTests.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
Labels: chore

#1552 ThreeDS2Component: Update 3ds2sdk to version 2.4.1
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
Labels: changed

#1543 Adding Privacy Manifest
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Package.swift
  PrivacyInfo.xcprivacy
  spell-check-word-allow-list.yaml
Labels: new, chore

#1551 V4: ThreeDS2Component: Update 3ds2sdk to version 2.4.1
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
Labels: changed

#1557 `v4` Add privacy manifest
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Package.swift
  PrivacyInfo.xcprivacy
Labels: new

#1558 Update generate_docc_documentation.sh
  Scripts/generate_docc_documentation.sh
Labels: chore

#1556 Allow configuration of showing country flags
  Adyen.docc/Customization.md
  Adyen/UI/Form/Items/Address/AddressStyle.swift
  Adyen/UI/Form/Items/Address/FormAddressItem.swift
  Adyen/UI/Styles/FormComponentStyle.swift
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Configuration.swift
  Tests/Adyen Tests/UI/Form/FormItems/Address/FormAddressPickerItemTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressInputFormViewControllerTests.swift
Labels: new

#1571 Revert "Format project" because of Swiftformat rules that break the pipeline
  Adyen/Core/AdyenContext/AdyenContext.swift
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Core Protocols/TrackableComponent.swift
  Adyen/Helpers/StringHelpers.swift
  Adyen/UI/List/ListViewController.swift
  Adyen/UI/Views/LinkTextView.swift
  Adyen/Utilities/Observable/EventPublisher.swift
  Adyen/Utilities/Observable/ObservationManager.swift
  Adyen/Utilities/PublicKeyProvider/PublicKeyProvider.swift
  AdyenActions/UI/View Controllers/Voucher/VoucherCardView.swift
  AdyenComponents/BACS Direct Debit/Trackers/BACSDirectDebitComponentTracker.swift
  AdyenDropIn/Components/PreselectedPaymentMethodComponent.swift
  Package.swift
  Tests/Actions Tests/Voucher/AppleWalletPassProviderTests.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
  Tests/Adyen Tests/Core/BackoffSchedulerTests.swift
  Tests/Adyen Tests/Core/SimpleSchedulerTests.swift
  Tests/Adyen Tests/UI/View Controllers/AddressLookupViewControllerTests.swift
  Tests/Adyen Tests/UI/View Controllers/FormPickerSearchViewControllerTests.swift
  Tests/AdyenSwiftUI Tests/AdyenSwiftUITests.swift
  Tests/Card Tests/CardPublicKeyProviderTests.swift
  Tests/Card Tests/Utilities/CardTypeDetectorTests.swift
  Tests/Card Tests/Utilities/ThrottlerTests.swift
  Tests/Card Tests/Validators/CardNumberValidatorTests.swift
  Tests/Components Tests/SEPA Tests/IBANValidatorTests.swift
  Tests/Session Tests/SelfRetainingAPIClientTests.swift
Labels: chore

#1531 Analytics event handling
  .swiftlint.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/Models/AdyenAnalytics.swift
  Adyen/Analytics/Models/AnalyticsEventDataSource.swift
  Adyen/Analytics/Models/AnalyticsEventError.swift
  Adyen/Analytics/Models/AnalyticsEventInfo.swift
  Adyen/Analytics/Models/AnalyticsEventLog.swift
  Adyen/Analytics/Models/ThreadSafeAnalyticsEventDataSource.swift
  Adyen/Core/AdyenContext/AdyenContext.swift
  Tests/Adyen Tests/Analytics/AnalyticsEventDataSourceTests.swift
  Tests/Adyen Tests/Analytics/AnalyticsEventTests.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderMock.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
Labels: chore

#1596 Updated snapshots
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsNotSet-iPhone12.shopper-info-prefilled-address-not-set.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsSet-iPhone12.shopper-info-prefilled-address-set.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testAffirm_givenNoShopperInformation_shouldNotPrefill-iPhone12.shopper-info-not-filled.png
  UITests/Components/Affirm/__Snapshots__/AffirmComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.shopper-info-prefilled.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAllRequiredTextField_shouldExist-iPhone12.all_required_fields_exist.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testAtome_givenNoShopperInformation_shouldNotPrefill-iPhone12.empty_form.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone12.prefilled_shopper_info.png
  UITests/Components/Atome/__Snapshots__/AtomeComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
  UITests/Components/MBWay/__Snapshots__/MBWayComponentUITests/testSubmitForm-iPhone12.mbway_flow.png
  UITests/Components/MBWay/__Snapshots__/MBWayComponentUITests/testUIConfiguration-iPhone12.UI_configuration.png
Labels: chore

#1593 Render and issuer list events
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/Models/AdyenAnalytics.swift
  Adyen/Analytics/Models/AnalyticsData.swift
  Adyen/Analytics/Models/AnalyticsEventError.swift
  Adyen/Analytics/Models/AnalyticsEventInfo.swift
  Adyen/Analytics/Models/AnalyticsEventLog.swift
  Adyen/Analytics/Requests/AnalyticsRequest.swift
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Components/StoredPaymentMethodComponent.swift
  Adyen/Core/Core Protocols/TrackableComponent.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentExtensions.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent+Extensions.swift
  AdyenCard/Components/Stored Card/StoredCardComponent.swift
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  AdyenComponents/BACS Direct Debit/Scenes/Input/BACSInputPresenter.swift
  AdyenComponents/BACS Direct Debit/Trackers/BACSDirectDebitComponentTracker.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenDropIn/Components/PreselectedPaymentMethodComponent.swift
  AdyenDropIn/DropInComponent.swift
  AdyenDropIn/DropInComponentExtensions.swift
  Tests/Adyen Tests/Analytics/AnalyticsProviderTests.swift
  Tests/Card Tests/BCMCComponentTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/Components Tests/Affirm/AffirmComponentTests.swift
  Tests/Components Tests/Apple Pay/ApplePayComponentTests.swift
  Tests/Components Tests/Atome/AtomeComponentTests.swift
  Tests/Components Tests/BACS Direct Debit/Mocks/BACSDirectDebitComponentTrackerProtocolMock.swift
  Tests/Components Tests/BACS Direct Debit/Trackers/BACSDirectDebitComponentTrackerTests.swift
  Tests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/Components Tests/Boleto/BoletoComponentTests.swift
  Tests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/Components Tests/Doku/DokuComponentTests.swift
  Tests/Components Tests/Gift Card/GiftCardComponentTests.swift
  Tests/Components Tests/IssuerList/IssuerListComponentTests.swift
  Tests/Components Tests/MB Way/MBWayComponentTests.swift
  Tests/Components Tests/Qiwi Wallet/QiwiWalletComponentTests.swift
  Tests/Components Tests/SEPA Tests/SEPADirectDebitComponentTests.swift
  Tests/DummyData/Dummy.swift
Labels: chore
