Repository Adyen/adyen-ios, pull requests merged in 2024-05, with the labels that each got.

#1661 Update localization documentation
  Adyen.docc/Customization.md
  Adyen.docc/Localization.md
Labels: chore

#1663 Fix package warnings
  Package.swift
Labels: chore

#1660 Change UPI tabs text
  AdyenComponents/UPI/UPIComponent.swift
Labels: chore

#1645 Convert more UI-based tests to unit tests
  Adyen/UI/Views/SubmitButton.swift
  AdyenActions/UI/View Controllers/Voucher/VoucherView.swift
  Tests/IntegrationTests/Actions Tests/Await/AwaitComponentTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/BoletoVoucherShareableVoucherViewProviderTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/DokuVoucherUITests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/EContextATMShareableVoucherViewProviderTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/EContextStoresVoucherViewControllerProviderTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/MultibancoShareableVoucherViewProviderTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/OXXOShareableVoucherViewProviderTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/VoucherComponentTests.swift
  Tests/IntegrationTests/Actions Tests/Voucher/VoucherViewTests.swift
  Tests/IntegrationTests/Card Tests/BCMCComponentTests.swift
  Tests/IntegrationTests/Helpers/XCTestCase+Style.swift
  Tests/IntegrationTests/Helpers/XCTestCase+Wait.swift
Labels: chore

#1667 Update .swiftlint.yml
  .swiftlint.yml
Labels: chore

#1671 Open external app detector tests
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/Redirect/OpenExternalAppDetector+DependencyKey.swift
  AdyenActions/Components/Redirect/OpenExternalAppDetector.swift
  Tests/IntegrationTests/Card Tests/Mocks/OpenExternalAppDetector+Mock.swift
  Tests/UnitTests/Core/OpenExternalAppDetectorTests.swift
Labels: chore

#1664 Only checking for .active on the `BrowserComponent`
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/Redirect/OpenExternalAppDetector+DependencyKey.swift
  AdyenActions/Components/Redirect/OpenExternalAppDetector.swift
  Tests/IntegrationTests/Card Tests/Mocks/OpenExternalAppDetector+Mock.swift
  Tests/UnitTests/Core/OpenExternalAppDetectorTests.swift
Labels: fixed

#1673 Docs: move list of available components to the page bottom
  Adyen.docc/Components.md
Labels: chore

#1670 Submit and 3ds events
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/Models/AnalyticsEventDataSource.swift
  Adyen/Analytics/Models/AnalyticsEventLog.swift
  Adyen/Analytics/Models/ThreadSafeAnalyticsEventDataSource.swift
  Adyen/Core/Core Protocols/PaymentComponent.swift
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2ClassicActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2CompactActionHandler.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/ApplePayComponentExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/CardComponentExample.swift
  Demo/Common/IntegrationExamples/Components/InstantPaymentComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/InstantPaymentComponentExample.swift
  Demo/Common/IntegrationExamples/Components/IssuerListComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Components/IssuerListComponentExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataAdvancedFlowProtocol.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/AdyenActionComponentTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
  Tests/IntegrationTests/Components Tests/PaymentComponent/PaymentComponentSubjectTests.swift
  Tests/UnitTests/Analytics/AnalyticsEventDataSourceTests.swift
Labels: chore

#1680 Fix publish demo app job
  .github/workflows/publish-demo-app.yml
  Adyen.xcodeproj/project.pbxproj
  AdyenCashAppPay/Info.plist
  AdyenDelegatedAuthentication/Info.plist
  AdyenSession/Info.plist
  AdyenTwint/Info.plist
  Package.swift
Labels: chore

#1687 Adding support for iDeal 2.0
  Adyen.docc/API Reference.md
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/IssuerListPaymentMethod.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenComponents/Issuer List/IssuerListDetails.swift
  Demo/Common/Assets/payment_methods_response.json
  Demo/SwiftUI/ComponentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
  README.md
  Tests/IntegrationTests/DropIn Tests/DropInTests.swift
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPad13-18-iPadOS_17-2-de_DE.initial_state.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPad13-18-iPadOS_17-2-de_DE.loading_first_cell.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPad13-18-iPadOS_17-2-de_DE.stopped_loading.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPad13-18-iPadOS_17-2-en_US.initial_state.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPad13-18-iPadOS_17-2-en_US.loading_first_cell.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPad13-18-iPadOS_17-2-en_US.stopped_loading.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone16-1-iOS_17-2-de_DE.initial_state.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone16-1-iOS_17-2-de_DE.loading_first_cell.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone16-1-iOS_17-2-de_DE.stopped_loading.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone16-1-iOS_17-2-en_US.initial_state.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone16-1-iOS_17-2-en_US.loading_first_cell.png
  Tests/SnapshotTests/Components/__Snapshots__/IssuerListComponentUITests/testStartStopLoading-iPhone16-1-iOS_17-2-en_US.stopped_loading.png
  Tests/UnitTests/Core/PaymentMethodTests.swift
  Tests/UnitTests/Mocks/DummyData/DummyPaymentMethods.swift
Labels: new

#1690 [V4] Adding support for iDeal 2.0
  .jazzy.yaml
  Adyen/Core/Payment Methods/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/IssuerListPaymentMethod.swift
  AdyenComponents/Issuer List/IssuerListComponent.swift
  AdyenComponents/Issuer List/IssuerListDetails.swift
  Demo/Common/Assets/payment_methods_response.json
  Demo/Common/IntegrationExampleComponents.swift
  Demo/SwiftUI/PaymentsViewModel.swift
  Demo/UIKit/ComponentsViewController.swift
  Demo/UIKit/PaymentMethods.json
  README.md
  Tests/AdyenTests/Adyen Tests/Core/PaymentMethodTests.swift
  Tests/AdyenTests/Adyen Tests/Core/TestPaymentMethodsJson.swift
  Tests/AdyenTests/Adyen Tests/DropIn/DropInTests.swift
Labels: new

#1700 Demo app cleanup
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/172.png
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/196.png
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/216.png
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/48.png
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/55.png
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/88.png
  Demo/SwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json
  Demo/SwiftUI/ComponentsViewModel.swift
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/172.png
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/196.png
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/216.png
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/48.png
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/55.png
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/88.png
  Demo/UIKit/Assets.xcassets/AppIcon.appiconset/Contents.json
  Demo/UIKit/Assets.xcassets/background.imageset/Background.png
  Demo/UIKit/Assets.xcassets/background.imageset/Background@2x.png
  Demo/UIKit/Assets.xcassets/background.imageset/Background@3x.png
  Demo/UIKit/Assets.xcassets/background.imageset/Contents.json
  Demo/UIKit/Assets.xcassets/checkout-button.imageset/Btn_cta.png
  Demo/UIKit/Assets.xcassets/checkout-button.imageset/Btn_cta@2x.png
  Demo/UIKit/Assets.xcassets/checkout-button.imageset/Btn_cta@3x.png
  Demo/UIKit/Assets.xcassets/checkout-button.imageset/Contents.json
  Demo/UIKit/Assets.xcassets/shopping-cart.imageset/Checkout window.png
  Demo/UIKit/Assets.xcassets/shopping-cart.imageset/Checkout window@2x.png
  Demo/UIKit/Assets.xcassets/shopping-cart.imageset/Checkout window@3x.png
  Demo/UIKit/Assets.xcassets/shopping-cart.imageset/Contents.json
  Demo/UIKit/ComponentsViewController.swift
  Tests/IntegrationTests/Card Tests/CardComponentTests.swift
  Tests/IntegrationTests/DropIn Tests/ModalToolbarTests.swift
Labels: chore
