Repository Adyen/adyen-ios, pull requests merged in 2024-10, with the labels that each got.

#1842 Fix crash: duplicate items when rendering payment methods list
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/List/ListItem.swift
  Demo/Configuration.swift
  Tests/AdyenTests/Adyen Tests/Core/ListItemTests.swift
  Tests/AdyenTests/Card Tests/CardComponentTests.swift
Labels: chore, v4

#1846 Add Github workflow to ensure ticket reference is present
  .github/workflows/validate_youtrack_ticket.yml
Labels: chore

#1841 Refactor SubmitCustomizable protocol
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/SnapshotTests.xcscheme
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Core Protocols/SubmittableComponent.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentExtensions.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenCashAppPay/CashAppPayComponent.swift
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  AdyenComponents/BLIK/BLIKComponent.swift
  AdyenComponents/Boleto/BoletoComponent.swift
  AdyenComponents/OnlineBanking/OnlineBankingComponent.swift
  AdyenComponents/SEPA Direct Debit/SEPADirectDebitComponent.swift
  AdyenComponents/UPI/UPIComponent.swift
  Tests/IntegrationTests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/IntegrationTests/Components Tests/Boleto/BoletoComponentTests.swift
  Tests/IntegrationTests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/IntegrationTests/Components Tests/Online Banking/OnlineBankingComponentTests.swift
  Tests/IntegrationTests/Components Tests/SEPA Tests/SEPADirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/UPIComponent/UPIComponentTests.swift
  Tests/SnapshotTests/Components/DokuComponentUITests.swift
Labels: changed

#1849 Exclude bot PRs from ticket checks
  .github/workflows/validate_ticket.yml
Labels: chore

#1850 chore: set special attemptId in payments object on fetch fail
  Adyen/Analytics/Models/AnalyticsConstants.swift
  Adyen/Core/Core Protocols/PaymentComponent.swift
  Tests/IntegrationTests/Components Tests/PaymentComponent/PaymentComponentSubjectTests.swift
Labels: chore

#1847 Create pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#1858 [public-api-diff] Bumping xcode version + fixing ad hoc diff
  .github/workflows/detect_api_changes.yml
Labels: chore

#1765 COIOS-748: Support tokenization for Twint payment
  Adyen.docc/API Reference.md
  Adyen.docc/Components.md
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Core Protocols/PaymentComponentBuilder.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/StoredTwintPaymentMethod.swift
  AdyenActions/Actions/TwintSDKData.swift
  AdyenActions/Components/SDK/Twint+Injectable.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  AdyenDropIn/DropInComponent.swift
  AdyenDropIn/Models/DropInConfiguration.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
  AdyenTwint/TwintComponent.swift
  Scripts/test-carthage-integration.sh
  Tests/IntegrationTests/Actions Tests/ActionComponent/AdyenActionComponentTests.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/Twint+Spy.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Convenience.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Flows.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
  Tests/IntegrationTests/Card Tests/StoredPaymentMethodComponentTests.swift
  Tests/IntegrationTests/Components Tests/Twint/TwintComponentTests.swift
  Tests/IntegrationTests/DropIn Tests/ComponentManagerTests.swift
  Tests/IntegrationTests/DropIn Tests/DropInTests.swift
  Tests/UnitTests/Mocks/DummyData/DummyPaymentMethods.swift
  Tests/UnitTests/Mocks/PaymentComponentMock.swift
  spell-check-word-allow-list.yaml
Labels: new

#1867 Fix failing compatibility tests
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
Labels: fixed

#1866 Add an event for closing the dropin
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/Models/AnalyticsEventLog.swift
  AdyenDropIn/DropInComponent.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
Labels: chore

#1868 Add new workflow to close stale issues (dry-run mode first)
  .github/workflows/stale_issues.yml
Labels: chore

#1870 Stale issues autoclose: remove debug mode
  .github/workflows/stale_issues.yml
Labels: chore

#1871 Exclude SPM packages from Swiftlint run
  .swiftlint.yml
Labels: chore

#1861 AUTHN-1928: Consume PaymentInfo for Delegated authentication
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDAScreenPresenter.swift
  AdyenActions/Components/3DS2/PaymentInfo.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentChallengeToken.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprintToken.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DAApprovalViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DARegistrationViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationErrorView.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationView.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/ViewHelpers/UILabelHelper.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2DAScreenPresenterMock.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests+Constants.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: changed

#1816 COIOS-774: Pay by Bank - Stored improvements
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Adyen/Core/Payment Methods/StoredPayByBankPaymentMethod.swift
Labels: chore

#1874 COIOS-755: Credit card field cursor fix
  Adyen/UI/Form/Items/Text/FormTextItem.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  AdyenCard/Form/FormCardNumberItem.swift
  AdyenCard/Form/FormCardNumberItemView.swift
  Tests/IntegrationTests/Card Tests/Items/CardNumberItem/FormCardNumberItemTests.swift
  Tests/IntegrationTests/Card Tests/Items/CardNumberItem/FormCardNumberItemViewTests.swift
Labels: fixed

#1872 Update Cashapp SDK version
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Package.swift
Labels: changed

#1882 Warnings cleanup
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Model/PrefilledShopperInformation.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressInputFormViewController.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationView.swift
  AdyenCard/Form/FormCardLogosItemView.swift
  AdyenComponents/UPI/UPIComponent.swift
  AdyenEncryption/Extensions/JSONEncoder+SortedKeys.swift
  Tests/SnapshotTests/Components/CardComponentUITests.swift
Labels: chore

#1876 COIOS-774: Pay by Bank - Confirmation Sheet
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Core/Core Protocols/PaymentComponentBuilder.swift
  Adyen/Core/Models/DisplayInformation.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Adyen/Core/Payment Methods/PayByBankUSPaymentMethod.swift
  Adyen/Core/Payment Methods/StoredPayByBankUSPaymentMethod.swift
  Adyen/Helpers/UIImageViewHelpers.swift
  Adyen/Helpers/UILabelHelpers.swift
  AdyenCard/Form/FormCardLogosItemView.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+Configuration.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+ConfirmationViewController.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+Style.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
Labels: chore

#1881 Introduce SDK lifecycle strategy
  README.md
Labels: chore

#1877 COIOS-774: Add logos as option for trailing view in ListItem
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Core Protocols/PaymentMethod.swift
  Adyen/Core/Models/DisplayInformation.swift
  Adyen/Helpers/UIImageViewHelpers.swift
  Adyen/UI/Form/Items/Value/Picker/FormPickerSearchViewController.swift
  Adyen/UI/List/ListItem.swift
  Adyen/UI/List/ListItemView.swift
  Adyen/UI/Views/SupportedPaymentMethodsView.swift
  AdyenDropIn/Components/PaymentMethodListComponent.swift
  Tests/IntegrationTests/UIKit/Views/SupportedPaymentMethodLogosViewTests.swift
  Tests/UnitTests/Core/ListItemTests.swift
Labels: chore

#1873 Enable `FormItemToggleView` external testability
  .gitignore
  Adyen/UI/Form/Items/Toggle/FormToggleItemView.swift
Labels: changed

#1885 Card number text field fix
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  AdyenCard/Form/FormCardNumberItemView.swift
  Tests/IntegrationTests/Card Tests/FormViewControllerTests.swift
  Tests/IntegrationTests/Card Tests/Items/CardNumberItem/FormCardNumberItemViewTests.swift
  Tests/IntegrationTests/UIKit/Form/FormItems/Text/FormTextItemViewDelegateMock.swift
  Tests/IntegrationTests/UIKit/Form/FormItems/Text/FormTextItemViewTests.swift
Labels: chore
