Repository Adyen/adyen-ios, pull requests merged in 2024-08, with the labels that each got.

#1759 [FIX] Address prefill reset
  Adyen/UI/Form/Items/Address/Picker/FormAddressPickerItem.swift
  Adyen/UI/View Controllers/AddressLookup/Form/AddressInputFormViewController.swift
  Tests/IntegrationTests/UIKit/Form/FormItems/Address/FormAddressPickerItemTests.swift
Labels: fixed

#1756 String only dictionary property for render event on analytics
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/Models/AdyenAnalytics.swift
  Adyen/Analytics/Models/AnalyticsEventError.swift
  Adyen/Analytics/Models/AnalyticsEventInfo.swift
  Adyen/Analytics/Models/AnalyticsEventLog.swift
  Adyen/Core/Components/Installment/InstallmentOptions.swift
  AdyenCard/Components/Card/CardAnalyticsConfiguration.swift
  AdyenCard/Components/Card/CardComponentExtensions.swift
  AdyenDropIn/DropInComponentExtensions.swift
  AdyenDropIn/Models/DropInAnalyticsConfiguration.swift
  Scripts/test-carthage-integration.sh
  Tests/IntegrationTests/Card Tests/CardComponentEventTests.swift
  Tests/IntegrationTests/DropIn Tests/DropInTests.swift
  spell-check-word-allow-list.yaml
Labels: chore

#1766 Also surfaces nested changes
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump+DeclarationType.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump+Element.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/SDKDumpAnalyzer.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpAnalyzerTests.swift
Labels: chore

#1768 Fix mismatching values with web for analytics config
  AdyenCard/Components/Card/CardAnalyticsConfiguration.swift
  Tests/IntegrationTests/Card Tests/CardComponentEventTests.swift
Labels: chore

#1772 [public-api-diff] (1/3) Adding description associated value to Change enum
  Scripts/public-api-diff/Sources/Helpers/Models/Change.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump+Element+Definition.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump+Element.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/LibraryAnalyzer.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/MarkdownOutputGenerator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/SDKDumpAnalyzer.swift
  Scripts/public-api-diff/Sources/Pipeline/Pipeline.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/LibraryAnalyzerTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/OutputGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/PipelineTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpAnalyzerTests.swift
Labels: chore

#1773 [public-api-diff] (2/3) change list
  Scripts/public-api-diff/Sources/Helpers/Models/Change.swift
  Scripts/public-api-diff/Sources/Helpers/Models/IndependentChange.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump+Conformance.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump+Element+Difference.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/MarkdownOutputGenerator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/SDKDumpAnalyzer/ChangeConsolidator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/SDKDumpAnalyzer/SDKDumpAnalyzer.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/OutputGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpAnalyzerTests.swift
Labels: chore

#1781 [public-api-diff] Applying formatting
  Scripts/public-api-diff/Sources/Helpers/Git.swift
  Scripts/public-api-diff/Sources/Helpers/Models/Constants.swift
  Scripts/public-api-diff/Sources/Helpers/Models/IndependentChange.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/ElementDescriptions/EnumCaseElement.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/ElementDescriptions/FunctionElement.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/ElementDescriptions/TypeAliasElement.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/ElementDescriptions/VarElement.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/SDKDump+Element+Description.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/SDKDump+Element+Difference.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/SDKDump+Element.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/SDKDump+Kind.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SDKDump/SDKDump.swift
  Scripts/public-api-diff/Sources/Helpers/Models/SwiftPackageDescription.swift
  Scripts/public-api-diff/Sources/Helpers/PackageFileHelper.swift
  Scripts/public-api-diff/Sources/Helpers/PipelineLogger.swift
  Scripts/public-api-diff/Sources/Helpers/RandomStringGenerating.swift
  Scripts/public-api-diff/Sources/Helpers/XcodeTools.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/ABIGenerator/ABIGenerator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/ABIGenerator/PackageABIGenerator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/ABIGenerator/ProjectABIProvider.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/MarkdownOutputGenerator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/ProjectBuilder.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/SDKDumpAnalyzer/ChangeConsolidator.swift
  Scripts/public-api-diff/Sources/Pipeline/Modules/SDKDumpAnalyzer/SDKDumpAnalyzer.swift
  Scripts/public-api-diff/Sources/Pipeline/Pipeline+Protocols.swift
  Scripts/public-api-diff/Sources/Pipeline/Pipeline.swift
  Scripts/public-api-diff/Sources/Pipeline/PipelineError.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/ABIGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/LibraryAnalyzerTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/PipelineTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/ProjectBuilderTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpAnalyzerTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockLogger.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockPipelineModules/MockABIGenerator.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockPipelineModules/MockLibraryAnalyzer.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockPipelineModules/MockOutputGenerator.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockPipelineModules/MockProjectBuilder.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockPipelineModules/MockSDKDumpAnalyzer.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockPipelineModules/MockSDKDumpGenerator.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockRandomStringGenerator.swift
Labels: chore

#1779 Update privacy manifest path to ensure correct SPM integration
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Adyen/PrivacyInfo.xcprivacy
Labels: fixed

#1784 Removing cashAppPayEnabled setting from demo app
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Common/Configuration/DropInSettingsView.swift
  Demo/Configuration.swift
Labels: chore

#1787 Removing Hidable protocol and adding it to FormItem
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/Form/Items/Address/FormAddressItem.swift
  Adyen/UI/Form/Items/Address/Picker/FormAddressPickerItem.swift
  Adyen/UI/Form/Items/Basic Items/FormAttributedLabelItem.swift
  Adyen/UI/Form/Items/Basic Items/FormContainerItem.swift
  Adyen/UI/Form/Items/Basic Items/FormLabelItem.swift
  Adyen/UI/Form/Items/Basic Items/FormVerticalStackItemView.swift
  Adyen/UI/Form/Items/Button/FormButtonItem.swift
  Adyen/UI/Form/Items/Button/SearchButton/FormSearchButtonItem.swift
  Adyen/UI/Form/Items/Error/FormErrorItem.swift
  Adyen/UI/Form/Items/FormImageItem/FormImageItem.swift
  Adyen/UI/Form/Items/FormItem.swift
  Adyen/UI/Form/Items/Segmented Control/FormSegmentedControlItem.swift
  Adyen/UI/Form/Items/SelectableFormItem/SelectableFormItem.swift
  Adyen/UI/Form/Items/Separator/FormSeparatorItem.swift
  Adyen/UI/Form/Items/Spacer/FormSpacerItem.swift
  Adyen/UI/Form/Items/Split/FormSplitItem.swift
  Adyen/UI/Form/Items/Text/FormTextInputItem.swift
  Adyen/UI/Form/Items/Toggle/FormToggleItem.swift
  Adyen/UI/Form/Items/Value Pickers/Abstract/BaseFormPickerItem.swift
  Adyen/UI/Form/Items/Value/FormValueItem.swift
  Adyen/UI/List/ListItem.swift
  AdyenCard/Form/FormCardExpiryDateItem.swift
  AdyenCard/Form/FormCardNumberContainerItem.swift
  AdyenCashAppPay/CashAppPayButton/CashAppPayButtonItem.swift
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  AdyenComponents/BLIK/BLIKComponent.swift
  AdyenComponents/OnlineBanking/OnlineBankingComponent.swift
  AdyenComponents/UPI/UPIComponent.swift
  AdyenDropIn/Components/PreselectedPaymentMethodComponent.swift
Labels: chore

#1793 Making anchor behave like expected
  Adyen/Helpers/UIViewConstraintsHelper.swift
  Adyen/UI/Form/Items/Basic Items/FormContainerItem.swift
  Adyen/UI/Form/Items/Button/SearchButton/FormSearchButtonItemView.swift
  Adyen/UI/Form/Items/Error/FormErrorItemView.swift
  Adyen/UI/Form/Items/Phone Number/Phone Extension Picker/FormPhoneExtensionPickerItemView.swift
  Adyen/UI/Form/Items/Value Pickers/Abstract/BasePickerInputControl.swift
  Adyen/UI/List/ListFooterView.swift
  AdyenActions/UI/View Controllers/Document/DocumentActionView.swift
  AdyenActions/UI/View Controllers/Voucher/ShareableVoucherView.swift
  AdyenActions/UI/View Controllers/Voucher/VoucherCardView.swift
  AdyenCard/Form/FormCardLogosItemView.swift
  Demo/UIKit/ComponentsView.swift
Labels: chore

#1788 Add validation function to SubmitCustomizable components
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent+Extensions.swift
  Adyen/Core/Components/AbstractPersonalInformationComponent/AbstractPersonalInformationComponent.swift
  Adyen/Core/Core Protocols/SubmitCustomizable.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardComponentExtensions.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenCashAppPay/CashAppPayComponent.swift
  AdyenComponents/ACH Direct Debit/ACHDirectDebitComponent.swift
  AdyenComponents/BLIK/BLIKComponent.swift
  AdyenComponents/OnlineBanking/OnlineBankingComponent.swift
  AdyenComponents/SEPA Direct Debit/SEPADirectDebitComponent.swift
  AdyenComponents/UPI/UPIComponent.swift
  Demo/UIKit/CustomComponent/CustomComponentPresenter.swift
  Demo/UIKit/CustomComponent/CustomComponentViewController.swift
  Tests/IntegrationTests/Card Tests/CardComponentTests.swift
  Tests/IntegrationTests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/IntegrationTests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/IntegrationTests/Components Tests/Gift Card/GiftCardComponentTests.swift
  Tests/IntegrationTests/Components Tests/Online Banking/OnlineBankingComponentTests.swift
  Tests/IntegrationTests/Components Tests/SEPA Tests/SEPADirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/UPIComponent/UPIComponentTests.swift
  Tests/SnapshotTests/Components/DokuComponentUITests.swift
Labels: new
