Repository Adyen/adyen-ios, pull requests merged in 2024-07, with the labels that each got.

#1718 [MVP] Switching to a swift command line tool
  .github/workflows/detect_api_changes.yml
  .gitignore
  Scripts/detect_public_api_changes/compare.sh
  Scripts/detect_public_api_changes/diff.swift
  Scripts/detect_public_api_changes/package_file_helper.swift
  Scripts/public-api-diff/Package.swift
  Scripts/public-api-diff/Sources/Helpers/FileHandling/FileHandling+Convenience.swift
  Scripts/public-api-diff/Sources/Helpers/FileHandling/FileHandling.swift
  Scripts/public-api-diff/Sources/Helpers/FileHandling/FileManager+FileHandling.swift
  Scripts/public-api-diff/Sources/Helpers/Git.swift
  Scripts/public-api-diff/Sources/Helpers/OutputGenerator.swift
  Scripts/public-api-diff/Sources/Helpers/PackageFileHelper.swift
  Scripts/public-api-diff/Sources/Helpers/ProjectHelper.swift
  Scripts/public-api-diff/Sources/Helpers/ProjectSource.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKAnalyzer+Change.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKAnalyzer.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/SDKDump+Models.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/SDKDumpGenerator.swift
  Scripts/public-api-diff/Sources/Helpers/Shell.swift
  Scripts/public-api-diff/Sources/Helpers/XcodeTools.swift
  Scripts/public-api-diff/Sources/public-api-diff.swift
  Scripts/public-api-diff/Tests/OutputGeneratorTests/OutputGeneratorTests.swift
Labels: chore

#1729 [UPI] Show error instead of disabled button
  .swiftlint.yml
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/ar.lproj/Localizable.strings
  Adyen/Assets/cs-CZ.lproj/Localizable.strings
  Adyen/Assets/da-DK.lproj/Localizable.strings
  Adyen/Assets/de-DE.lproj/Localizable.strings
  Adyen/Assets/el-GR.lproj/Localizable.strings
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Assets/es-ES.lproj/Localizable.strings
  Adyen/Assets/fi.lproj/Localizable.strings
  Adyen/Assets/fr-FR.lproj/Localizable.strings
  Adyen/Assets/hr-HR.lproj/Localizable.strings
  Adyen/Assets/hu-HU.lproj/Localizable.strings
  Adyen/Assets/it-IT.lproj/Localizable.strings
  Adyen/Assets/ja-JP.lproj/Localizable.strings
  Adyen/Assets/ko.lproj/Localizable.strings
  Adyen/Assets/nb-NO.lproj/Localizable.strings
  Adyen/Assets/nl-NL.lproj/Localizable.strings
  Adyen/Assets/pl-PL.lproj/Localizable.strings
  Adyen/Assets/pt-BR.lproj/Localizable.strings
  Adyen/Assets/pt-PT.lproj/Localizable.strings
  Adyen/Assets/ro-RO.lproj/Localizable.strings
  Adyen/Assets/ru-RU.lproj/Localizable.strings
  Adyen/Assets/sk-SK.lproj/Localizable.strings
  Adyen/Assets/sl-SI.lproj/Localizable.strings
  Adyen/Assets/sv-SE.lproj/Localizable.strings
  Adyen/Assets/zh-CN.lproj/Localizable.strings
  Adyen/Assets/zh-TW.lproj/Localizable.strings
  Adyen/UI/Form/Items/Error/FormErrorItem.swift
  Adyen/UI/Form/Items/Error/FormErrorItemView.swift
  AdyenActions/Components/Await/AwaitComponent.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenComponents/UPI/UPIComponent.swift
  Scripts/public-api-diff/Sources/Helpers/ProjectSource.swift
  Tests/IntegrationTests/Components Tests/UPIComponent/UPIComponentTests.swift
  Tests/SnapshotTests/Components/UPIComponentUITests.swift
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPad13-18-iPadOS_17-2-ar_AE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPad13-18-iPadOS_17-2-de_DE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPad13-18-iPadOS_17-2-en_US.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPhone16-1-iOS_17-2-ar_AE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPhone16-1-iOS_17-2-de_DE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPhone16-1-iOS_17-2-en_US.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPad13-18-iPadOS_17-2-ar_AE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPad13-18-iPadOS_17-2-de_DE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPad13-18-iPadOS_17-2-en_US.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPhone16-1-iOS_17-2-ar_AE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPhone16-1-iOS_17-2-de_DE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPhone16-1-iOS_17-2-en_US.upi_no_app_selected_submit.png
  Tests/UnitTests/Mocks/DummyData/DummyPaymentMethods.swift
  spell-check-word-allow-list.yaml
Labels: chore

#1740 Update .swiftlint.yml
  .swiftlint.yml
Labels: chore

#1727 [SwiftPackageAPIDiff] Adding Initial Tests
  .github/workflows/detect_api_changes.yml
  Scripts/public-api-diff/Package.swift
  Scripts/public-api-diff/Sources/Helpers/FileHandling/FileHandling+Convenience.swift
  Scripts/public-api-diff/Sources/Helpers/FileHandling/FileHandling.swift
  Scripts/public-api-diff/Sources/Helpers/FileHandling/FileManager+FileHandling.swift
  Scripts/public-api-diff/Sources/Helpers/Git.swift
  Scripts/public-api-diff/Sources/Helpers/PackageFileHelper.swift
  Scripts/public-api-diff/Sources/Helpers/ProjectHelper.swift
  Scripts/public-api-diff/Sources/Helpers/ProjectSource.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/PackageAnalyzer.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKAnalyzer+Change.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKAnalyzer.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKDumpAnalyzer.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/Models/SDKDump+Conformance.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/Models/SDKDump+DeclarationType.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/Models/SDKDump+Element.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/Models/SDKDump.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/SDKDump+Models.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/SDKDumpGenerator.swift
  Scripts/public-api-diff/Sources/Helpers/XcodeTools.swift
  Scripts/public-api-diff/Sources/public-api-diff.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/FileHandlingTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/GitTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/OutputGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/ProjectSourceTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Resources/NewPackage.txt
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Resources/OldPackage.txt
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Resources/api_dump.json
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKAnalyzerTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpAnalyzerTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockFileHandler.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/Utilities/MockShell.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/XcodeToolsTests.swift
Labels: chore

#1737 Verbose function and var names
  Scripts/public-api-diff/Sources/Helpers/MarkdownOutputGenerator.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKAnalyzer+Change.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKAnalyzer.swift
  Scripts/public-api-diff/Sources/Helpers/SDKAnalyzer/SDKDumpAnalyzer.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/Models/SDKDump+Element.swift
  Scripts/public-api-diff/Sources/Helpers/SDKDumpGenerator/Models/SDKDump.swift
  Scripts/public-api-diff/Sources/public-api-diff.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/OutputGeneratorTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKAnalyzerTests.swift
  Scripts/public-api-diff/Tests/PublicApiDiffTests/SDKDumpAnalyzerTests.swift
Labels: chore

#1742 Updating translations + adding new locales
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/ar.lproj/Localizable.strings
  Adyen/Assets/bg-BG.lproj/Localizable.strings
  Adyen/Assets/ca-ES.lproj/Localizable.strings
  Adyen/Assets/cs-CZ.lproj/Localizable.strings
  Adyen/Assets/da-DK.lproj/Localizable.strings
  Adyen/Assets/de-DE.lproj/Localizable.strings
  Adyen/Assets/el-GR.lproj/Localizable.strings
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Assets/es-ES.lproj/Localizable.strings
  Adyen/Assets/et-EE.lproj/Localizable.strings
  Adyen/Assets/fi.lproj/Localizable.strings
  Adyen/Assets/fr-FR.lproj/Localizable.strings
  Adyen/Assets/hr-HR.lproj/Localizable.strings
  Adyen/Assets/hu-HU.lproj/Localizable.strings
  Adyen/Assets/is-IS.lproj/Localizable.strings
  Adyen/Assets/it-IT.lproj/Localizable.strings
  Adyen/Assets/ja-JP.lproj/Localizable.strings
  Adyen/Assets/ko.lproj/Localizable.strings
  Adyen/Assets/lt-LT.lproj/Localizable.strings
  Adyen/Assets/lv-LV.lproj/Localizable.strings
  Adyen/Assets/nb-NO.lproj/Localizable.strings
  Adyen/Assets/nl-NL.lproj/Localizable.strings
  Adyen/Assets/pl-PL.lproj/Localizable.strings
  Adyen/Assets/pt-BR.lproj/Localizable.strings
  Adyen/Assets/pt-PT.lproj/Localizable.strings
  Adyen/Assets/ro-RO.lproj/Localizable.strings
  Adyen/Assets/ru-RU.lproj/Localizable.strings
  Adyen/Assets/sk-SK.lproj/Localizable.strings
  Adyen/Assets/sl-SI.lproj/Localizable.strings
  Adyen/Assets/sv-SE.lproj/Localizable.strings
  Adyen/Assets/zh-CN.lproj/Localizable.strings
  Adyen/Assets/zh-TW.lproj/Localizable.strings
Labels: new

#1709 DropIn stored payment method removal via session
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Core Protocols/DropInComponentDelegate.swift
  Adyen/Core/Core Protocols/StorePaymentMethodFieldAware.swift
  Adyen/Core/Core Protocols/StoredPaymentMethodsDelegate.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Adyen/Model/PrefilledShopperInformation.swift
  Adyen/Model/StorePaymentMethodFieldAware.swift
  AdyenActions/UI/View Controllers/Await/AwaitComponentViewModel.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/GiftCardComponent/GiftCardComponent.swift
  AdyenDropIn/DropInComponent.swift
  AdyenDropIn/DropInComponentExtensions.swift
  AdyenDropIn/Utilities/ComponentManager.swift
  AdyenSession/API/Disable Stored Payments/DisableStoredPaymentMethodRequest.swift
  AdyenSession/API/Session Setup/SessionSetupRequest.swift
  AdyenSession/AdyenSession+StoredPaymentMethodsDelegate.swift
  Demo/Common/Configuration/DropInSettingsView.swift
  Demo/Common/IntegrationExamples/DropIn/DropInExample.swift
  Demo/Common/Networking/SessionRequest.swift
  Scripts/test-carthage-integration.sh
  Tests/IntegrationTests/Card Tests/3DS2 Component/3DS2 Fingerprint Submitter/ThreeDS2FingerprintSubmitterTests.swift
  Tests/IntegrationTests/DropIn Tests/DropInTests.swift
  Tests/IntegrationTests/DropIn Tests/StoredPaymentMethodDelegateMock.swift
  Tests/IntegrationTests/Session Tests/SessionTests.swift
Labels: new

#1748 Fix WeChat target
  Adyen.xcodeproj/project.pbxproj
Labels: chore

#1726 Delegated authentication - with newer screens
  .github/workflows/build.yml
  .github/workflows/test_cocoapods_integration.yml
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Assets/AdyenActionsAssets.xcassets/feedback.imageset/Contents.json
  AdyenActions/Assets/AdyenActionsAssets.xcassets/feedback.imageset/feedback.pdf
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDAScreenPresenter.swift
  AdyenActions/Components/3DS2/Action handlers/AnyThreeDS2ActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2ClassicActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/ThreeDS2CompactActionHandler.swift
  AdyenActions/Components/3DS2/ThreeDS2Component.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprint.swift
  AdyenActions/Components/3DS2/ThreeDSResult.swift
  AdyenActions/UI/UI Style/ActionComponentStyle.swift
  AdyenActions/UI/UI Style/DelegatedAuthenticationComponentStyle.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DAApprovalViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DAErrorViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DARegistrationViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationErrorView.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationView.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/ViewHelpers/UIImageViewHelper.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/ViewHelpers/UILabelHelper.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/ViewHelpers/UIStackViewHelper.swift
  AdyenCard/Components/Card/CardDetails.swift
  Cartfile
  Demo/Configuration.swift
  Demo/Shared.entitlements
  Package.swift
  Scripts/test-CocoaPods-integration.sh
  Scripts/test-SPM-integration.sh
  Scripts/test-carthage-integration.sh
  Tests/IntegrationTests/Card Tests/3DS2 Component/AnyThreeDS2ActionHandlerMock.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/AuthenticationServiceMock.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2CompactActionHandlerTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2DAScreenPresenterMock.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests+Constants.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
  spell-check-word-allow-list.yaml
Labels: changed

#1757 Cleaning up swiftpm
  Scripts/test-SPM-integration.sh
Labels: chore

#1761 Workflow fixes
  .github/workflows/test-SPM-integration.yml
  .swiftformat
Labels: chore

#1763 Format and spm
  .github/workflows/test-SPM-integration.yml
  Scripts/test-SPM-integration.sh
Labels: chore
