Repository Adyen/adyen-ios, pull requests merged in 2024-04, with the labels that each got.

#1603 Update README.md
  README.md
Labels: chore

#1594 Removing all usage of country flags
  Adyen.docc/Customization.md
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/ar.lproj/Localizable.strings
  Adyen/Assets/cs-CZ.lproj/Localizable.strings
  Adyen/Assets/da-DK.lproj/Localizable.strings
  Adyen/Assets/de-DE.lproj/Localizable.strings
  Adyen/Assets/el-GR.lproj/Localizable.strings
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Assets/es-ES.lproj/Localizable.strings
  Adyen/Assets/fi.lproj/Localizable.strings
  Adyen/Assets/fr-FR.lproj/Localizable.strings
  Adyen/Assets/hr-HR.lproj/Localizable.strings
  Adyen/Assets/hu-HU.lproj/Localizable.strings
  Adyen/Assets/it-IT.lproj/Localizable.strings
  Adyen/Assets/ja-JP.lproj/Localizable.strings
  Adyen/Assets/ko.lproj/Localizable.strings
  Adyen/Assets/nb-NO.lproj/Localizable.strings
  Adyen/Assets/nl-NL.lproj/Localizable.strings
  Adyen/Assets/pl-PL.lproj/Localizable.strings
  Adyen/Assets/pt-BR.lproj/Localizable.strings
  Adyen/Assets/pt-PT.lproj/Localizable.strings
  Adyen/Assets/ro-RO.lproj/Localizable.strings
  Adyen/Assets/ru-RU.lproj/Localizable.strings
  Adyen/Assets/sk-SK.lproj/Localizable.strings
  Adyen/Assets/sl-SI.lproj/Localizable.strings
  Adyen/Assets/sv-SE.lproj/Localizable.strings
  Adyen/Assets/zh-CN.lproj/Localizable.strings
  Adyen/Assets/zh-TW.lproj/Localizable.strings
  Adyen/Helpers/StringHelpers.swift
  Adyen/UI/Form/Items/Address/AddressStyle.swift
  Adyen/UI/Form/Items/Address/FormAddressItem.swift
  Adyen/UI/Form/Items/Address/FormRegionPickerItem.swift
  Adyen/UI/Form/Items/Value Pickers/Phone Extension Picker/FormPhoneExtensionPickerItemView.swift
  Adyen/UI/Form/Items/Value Pickers/Phone Extension Picker/PhoneExtensionInputControl.swift
  Adyen/Utilities/External/PhoneExtensionsRepository.swift
  Demo/Common/Configuration/CardComponentSettingsView.swift
  Demo/Common/Configuration/ConfigurationViewModel.swift
  Demo/Configuration.swift
  Tests/Adyen Tests/UI/View Controllers/AddressInputFormViewControllerTests.swift
  UITests/Components/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsNotSet-iPhone16-1-iOS_17-2.shopper-info-prefilled-address-not-set.png
  UITests/Components/__Snapshots__/AffirmComponentUITests/testAffirmPrefilling_givenDeliveryAddressIsSet-iPhone16-1-iOS_17-2.shopper-info-prefilled-address-set.png
  UITests/Components/__Snapshots__/AffirmComponentUITests/testAffirm_givenNoShopperInformation_shouldNotPrefill-iPhone16-1-iOS_17-2.shopper-info-not-filled.png
  UITests/Components/__Snapshots__/AffirmComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone16-1-iOS_17-2.shopper-info-prefilled.png
  UITests/Components/__Snapshots__/AtomeComponentUITests/testAllRequiredTextField_shouldExist-iPhone16-1-iOS_17-2.all_required_fields_exist.png
  UITests/Components/__Snapshots__/AtomeComponentUITests/testAtome_givenNoShopperInformation_shouldNotPrefill-iPhone16-1-iOS_17-2.empty_form.png
  UITests/Components/__Snapshots__/AtomeComponentUITests/testSubmitForm_shouldCallDelegateWithProperParameters-iPhone16-1-iOS_17-2.prefilled_shopper_info.png
  UITests/Components/__Snapshots__/AtomeComponentUITests/testUIConfiguration-iPhone16-1-iOS_17-2.UI_configuration.png
  UITests/Components/__Snapshots__/MBWayComponentUITests/testSubmitForm-iPhone16-1-iOS_17-2.mbway_flow.png
  UITests/Components/__Snapshots__/MBWayComponentUITests/testUIConfiguration-iPhone16-1-iOS_17-2.UI_configuration.png
Labels: changed, chore

#1614 Generating coverage for tests
  .github/workflows/pr_scan.yml
  TestPlans/AllTests.xctestplan
  TestPlans/GenerateSnapshots.xctestplan
  TestPlans/SnapshotTests.xctestplan
  TestPlans/UnitTests.xctestplan
Labels: chore

#1610 Create unit tests target and extract first batch of pure unit tests
  .swiftlint.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUnitTests.xcscheme
  AdyenUnitTests/APIClientMock.swift
  AdyenUnitTests/Analytics/AnalyticsEventDataSourceTests.swift
  AdyenUnitTests/Analytics/AnalyticsEventTests.swift
  AdyenUnitTests/Analytics/AnalyticsFlavorTests.swift
  AdyenUnitTests/Analytics/AnalyticsProviderMock.swift
  AdyenUnitTests/Analytics/AnalyticsProviderTests.swift
  Scripts/test-carthage-integration.sh
  TestPlans/AdyenUIHost.xctestplan
  TestPlans/AdyenUnitTests.xctestplan
  Tests/Helpers/XCTestCase+FormTextItemView.swift
  Tests/Helpers/XCTestCase+Wait+UIKit.swift
  Tests/Helpers/XCTestCase+Wait.swift
Labels: chore

#1617 Focus/unfocus events for card component
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/Models/AdyenAnalytics.swift
  Adyen/UI/Form/Items/Text/FormTextItem.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenUnitTests/Analytics/AnalyticsProviderMock.swift
  SnapshotTests/UI/SecuredViewControllerUITests.swift
  Tests/Card Tests/BCMCComponentTests.swift
  Tests/Card Tests/CardComponentEventTests.swift
  Tests/Card Tests/CardComponentTests.swift
  Tests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/Components Tests/Affirm/AffirmComponentTests.swift
  Tests/Components Tests/Apple Pay/ApplePayComponentTests.swift
  Tests/Components Tests/Atome/AtomeComponentTests.swift
  Tests/Components Tests/BACS Direct Debit/Trackers/BACSDirectDebitComponentTrackerTests.swift
  Tests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/Components Tests/Boleto/BoletoComponentTests.swift
  Tests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/Components Tests/Doku/DokuComponentTests.swift
  Tests/Components Tests/Gift Card/GiftCardComponentTests.swift
  Tests/Components Tests/IssuerList/IssuerListComponentTests.swift
  Tests/Components Tests/MB Way/MBWayComponentTests.swift
  Tests/Components Tests/Qiwi Wallet/QiwiWalletComponentTests.swift
  Tests/Components Tests/SEPA Tests/SEPADirectDebitComponentTests.swift
Labels: chore

#1624 Fix Compatibility tests workflow
  .github/workflows/build.yml
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/IntegrationUIKitTests.xcscheme
  TestPlans/IntegrationTests.xctestplan
Labels: chore

#1616 Fixing Testflight Publishing
  .github/workflows/publish-demo-app.yml
  Adyen.xcodeproj/project.pbxproj
Labels: chore

#1625 Remove slather and use script instead to feed coverage reports to Sonar
  .github/workflows/pr_scan.yml
  Adyen.xcodeproj/xcshareddata/xcschemes/SnapshotTests.xcscheme
  Scripts/xccov-to-sonarqube-generic.sh
  TestPlans/CI.xctestplan
  TestPlans/UnitTests.xctestplan
  sonar-project.properties
Labels: chore

#1631 Extract SwiftUI UI tests to a separate test plan
  .swiftlint.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenSwiftUIHost.xcscheme
  Adyen.xcodeproj/xcshareddata/xcschemes/SwiftUI-UITests.xcscheme
  AdyenUITests/AdyenSwiftUITests.swift
  AdyenUITests/Info.plist
  TestPlans/CI.xctestplan
  TestPlans/UITests.xctestplan
Labels: chore

#1628 FormItem validation for analytics
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/Models/AnalyticsValidationError.swift
  Adyen/UI/Form/Items/Text/FormTextItem.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItem.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItemView.swift
  Adyen/Validators/ClientKeyValidator.swift
  Adyen/Validators/CountryCodeValidator.swift
  Adyen/Validators/CurrencyCodeValidator.swift
  Adyen/Validators/DateValidator.swift
  Adyen/Validators/EmailValidator.swift
  Adyen/Validators/IBANValidator.swift
  Adyen/Validators/LengthValidator.swift
  Adyen/Validators/NumericStringValidator.swift
  Adyen/Validators/PhoneNumberValidator.swift
  Adyen/Validators/RegularExpressionValidator.swift
  Adyen/Validators/ValidationError.swift
  Adyen/Validators/Validator.swift
  AdyenCard/Components/Card/CardComponent.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenCard/Validators/CardExpiryDateValidator.swift
  AdyenCard/Validators/CardNumberValidator.swift
  AdyenCard/Validators/CardSecurityCodeValidator.swift
  AdyenCard/Validators/CardValidationError.swift
  AdyenIntegrationTests/Card Tests/CardComponentEventTests.swift
  AdyenIntegrationTests/Card Tests/CardComponentTests.swift
  AdyenIntegrationTests/Card Tests/Validators/CardNumberValidatorTests.swift
Labels: chore

#1634 More validators added for card component analytics
  Adyen/Analytics/Models/AnalyticsValidationError.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItemView.swift
  Adyen/Validators/NumericStringValidator.swift
  AdyenCard/Validators/CardExpiryDateValidator.swift
  AdyenCard/Validators/CardSecurityCodeValidator.swift
  Tests/IntegrationTests/Card Tests/CardComponentEventTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardExpiryDateValidatorTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardSecurityCodeValidatorTests.swift
Labels: chore

#1635 Fixing post-release-script
  .github/workflows/post_release.yml
Labels: chore

#1636 More validators added for analytics
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/Models/AnalyticsConstants.swift
  Adyen/Analytics/Models/AnalyticsEventLog.swift
  Adyen/UI/Form/Items/Address/FormPostalCodeItem.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItemView.swift
  Adyen/Validators/AddressAnalyticsValidationError.swift
  Adyen/Validators/BrazilSocialSecurityNumberValidator.swift
  Adyen/Validators/PostalCodeValidator.swift
  Adyen/Validators/Validator.swift
  AdyenCard/Components/Card/CardViewControllerItemsProvider.swift
  AdyenCard/Validators/CardExpiryDateValidator.swift
  AdyenCard/Validators/CardHolderNameValidator.swift
  AdyenCard/Validators/CardKCPValidators.swift
  AdyenCard/Validators/CardNumberValidator.swift
  AdyenCard/Validators/CardValidationError.swift
  Tests/IntegrationTests/Card Tests/CardComponentEventTests.swift
  Tests/IntegrationTests/Card Tests/Validators/BrazilSocialSecurityNumberValidatorTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardExpiryDateValidatorTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardHolderNameValidatorTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardKCPValidatorsTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardNumberValidatorTests.swift
  Tests/IntegrationTests/Card Tests/Validators/CardSecurityCodeValidatorTests.swift
  Tests/IntegrationTests/Card Tests/Validators/PostalCodeValidatorTests.swift
Labels: chore

#1644 Added changes related to status api call
  AdyenActions/Actions/AwaitAction.swift
  AdyenActions/Actions/TwintSDKAction.swift
  AdyenActions/Components/Await/PollingHandlerProvider.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  AdyenActions/UI/View Controllers/Await/AwaitComponentViewModel.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Convenience.swift
  Tests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Flows.swift
Labels: chore

#1653 V4 - Update version of 3ds2sdk to 2.4.2
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
Labels: changed

#1652 V5 - Update 3ds2sdk to version 2.4.2
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
Labels: changed
