Repository Adyen/adyen-ios, pull requests merged in 2024-11, with the labels that each got.

#1887 Relax ticket validation regex
  .github/workflows/validate_ticket.yml
Labels: chore

#1893 Minimum system version in plist file
  Demo/SwiftUI/Info.plist
  Demo/UIKit/Info.plist
Labels: chore

#1897 Allow voucher document saving on iPad
  AdyenActions/Components/Voucher/VoucherComponentExtensions.swift
Labels: new

#1884 Splitting responsibilities of analytics provider
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/AnalyticsProvider/AnalyticsProviderProtocol.swift
  Adyen/Analytics/AnalyticsProvider/EventAnalyticsProvider.swift
  Adyen/Core/AdyenContext/AdyenContext.swift
  Tests/UnitTests/Analytics/AnalyticsEventTests.swift
  Tests/UnitTests/Analytics/AnalyticsProviderMock.swift
  Tests/UnitTests/Analytics/AnalyticsProviderTests.swift
  Tests/UnitTests/Analytics/EventAnalyticsProviderTests.swift
  Tests/UnitTests/Core/AdyenContextTests.swift
  Tests/UnitTests/Mocks/DummyData/DummyHelper.swift
Labels: chore

#1883 AUTHN-2322: Add an option to reset DA/passkey & updating copies
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/en-US.lproj/Localizable.strings
  AdyenActions/Assets/AdyenActionsAssets.xcassets/cross-circle.imageset/Contents.json
  AdyenActions/Assets/AdyenActionsAssets.xcassets/cross-circle.imageset/cross-circle.pdf
  AdyenActions/Assets/AdyenActionsAssets.xcassets/feedback.imageset/feedback.pdf
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDAScreenPresenter.swift
  AdyenActions/UI/UI Style/DelegatedAuthenticationComponentStyle.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DAApprovalViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DAErrorViewController.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationErrorView.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationView.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/ViewHelpers/UIImageViewHelper.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/ViewHelpers/UIStackViewHelper.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2ComponentTests.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2DAScreenPresenterMock.swift
Labels: changed

#1891 AUTHN-2322: Secure checkout on auth cancellation we reset & authentication release 3.1.0
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/ar.lproj/Localizable.strings
  Adyen/Assets/bg-BG.lproj/Localizable.strings
  Adyen/Assets/ca-ES.lproj/Localizable.strings
  Adyen/Assets/cs-CZ.lproj/Localizable.strings
  Adyen/Assets/da-DK.lproj/Localizable.strings
  Adyen/Assets/de-DE.lproj/Localizable.strings
  Adyen/Assets/el-GR.lproj/Localizable.strings
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Assets/es-ES.lproj/Localizable.strings
  Adyen/Assets/et-EE.lproj/Localizable.strings
  Adyen/Assets/fi.lproj/Localizable.strings
  Adyen/Assets/fr-FR.lproj/Localizable.strings
  Adyen/Assets/hr-HR.lproj/Localizable.strings
  Adyen/Assets/hu-HU.lproj/Localizable.strings
  Adyen/Assets/is-IS.lproj/Localizable.strings
  Adyen/Assets/it-IT.lproj/Localizable.strings
  Adyen/Assets/ja-JP.lproj/Localizable.strings
  Adyen/Assets/ko.lproj/Localizable.strings
  Adyen/Assets/lt-LT.lproj/Localizable.strings
  Adyen/Assets/lv-LV.lproj/Localizable.strings
  Adyen/Assets/nb-NO.lproj/Localizable.strings
  Adyen/Assets/nl-NL.lproj/Localizable.strings
  Adyen/Assets/pl-PL.lproj/Localizable.strings
  Adyen/Assets/pt-BR.lproj/Localizable.strings
  Adyen/Assets/pt-PT.lproj/Localizable.strings
  Adyen/Assets/ro-RO.lproj/Localizable.strings
  Adyen/Assets/ru-RU.lproj/Localizable.strings
  Adyen/Assets/sk-SK.lproj/Localizable.strings
  Adyen/Assets/sl-SI.lproj/Localizable.strings
  Adyen/Assets/sv-SE.lproj/Localizable.strings
  Adyen/Assets/zh-CN.lproj/Localizable.strings
  Adyen/Assets/zh-TW.lproj/Localizable.strings
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  Cartfile
  Scripts/test-carthage-integration.sh
Labels: new

#1899 Fixing compatibility
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
Labels: chore

#1901 Send a new field to determine the analytics level in the initial call.
  .swiftformat
  Adyen/Analytics/AnalyticsProvider/AnalyticsProvider.swift
  Adyen/Analytics/Models/AdyenAnalytics.swift
  Adyen/Analytics/Models/AnalyticsData.swift
  Adyen/Analytics/Requests/InitialAnalyticsRequest.swift
  Adyen/Core/AdyenContext/AdyenContext.swift
  Tests/UnitTests/Analytics/AnalyticsEventTests.swift
  Tests/UnitTests/Analytics/AnalyticsProviderTests.swift
Labels: chore

#1878 COIOS-774: Pay by Bank
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Core/Core Protocols/PaymentComponentBuilder.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  Adyen/Core/Payment Methods/PayByBankUSPaymentMethod.swift
  Adyen/Core/Payment Methods/StoredPayByBankUSPaymentMethod.swift
  Adyen/Helpers/UIImageViewHelpers.swift
  Adyen/Helpers/UILabelHelpers.swift
  Adyen/UI/Views/SupportedPaymentMethodsView.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+Configuration.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+ConfirmationViewController+Model.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+ConfirmationViewController.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent+Style.swift
  AdyenComponents/PayByBank/US/PayByBankUSComponent.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
  Tests/IntegrationTests/Components Tests/PayByBankUSComponentTests.swift
Labels: new

#1903 COIOS-806: Support all Boleto Bancario tx-variants
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethod.swift
  Adyen/Core/Payment Methods/Abstract/AnyPaymentMethodDecoder.swift
  Adyen/Core/Payment Methods/Abstract/PaymentMethodType.swift
  AdyenActions/Actions/VoucherAction.swift
  AdyenActions/Components/Voucher/VoucherShareableViewProvider.swift
  Tests/IntegrationTests/Components Tests/Boleto/BoletoComponentTests.swift
  Tests/IntegrationTests/DropIn Tests/ComponentManagerTests.swift
  Tests/SnapshotTests/Components/BoletoComponentUITests.swift
  Tests/UnitTests/Core/PaymentMethodTests.swift
  Tests/UnitTests/Mocks/DummyData/DummyPaymentMethods.swift
  spell-check-word-allow-list.yaml
Labels: new

#1905 COIOS-834: Update TwintSDK to v8.0.2
  Adyen/Core/Core Protocols/SubmittableComponent.swift
  AdyenActions/Components/SDK/Twint+Injectable.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/Twint+Spy.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Flows.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
  XCFramework/Dynamic/TwintSDK.xcframework/Info.plist
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/Headers/Twint.h
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/Info.plist
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/Modules/module.modulemap
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/TwintSDK
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/Headers/Twint.h
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/Info.plist
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/Modules/module.modulemap
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/TwintSDK
  XCFramework/Dynamic/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/_CodeSignature/CodeResources
  XCFramework/Static/TwintSDK.xcframework/Info.plist
  XCFramework/Static/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/Headers/Twint.h
  XCFramework/Static/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/Info.plist
  XCFramework/Static/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/Modules/module.modulemap
  XCFramework/Static/TwintSDK.xcframework/ios-arm64/TwintSDK.framework/TwintSDK
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/Headers/Twint.h
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/Info.plist
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/Modules/module.modulemap
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/TwintSDK
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/_CodeSignature/CodeDirectory
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/_CodeSignature/CodeRequirements-1
  XCFramework/Static/TwintSDK.xcframework/ios-arm64_x86_64-simulator/TwintSDK.framework/_CodeSignature/CodeResources
Labels: new

#1904 Correcting `type` value for mealVoucher_FR
  AdyenCard/Components/GiftCardComponent/MealVoucherDetails.swift
  Tests/IntegrationTests/Components Tests/Gift Card/GiftCardComponentTests.swift
Labels: fixed

#1906 Remove default border in pay by bank confirmation screen
  AdyenComponents/PayByBank/US/PayByBankUSComponent+Style.swift
Labels: chore

#1907 Adding `maxIssuerNumber` to the Twint configuration
  AdyenActions/Components/SDK/Twint+Injectable.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/Twint+Spy.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Convenience.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Flows.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
Labels: new
