Repository Adyen/adyen-ios, pull requests merged in 2025-06, with the labels that each got.

#2149 COSDK-483 Conform Card component to European Accessibility Act
  .gitignore
  .swiftlint.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen/Assets/Generated/LocalizationKey.swift
  Adyen/Assets/ar.lproj/Localizable.strings
  Adyen/Assets/bg-BG.lproj/Localizable.strings
  Adyen/Assets/ca-ES.lproj/Localizable.strings
  Adyen/Assets/cs-CZ.lproj/Localizable.strings
  Adyen/Assets/da-DK.lproj/Localizable.strings
  Adyen/Assets/de-DE.lproj/Localizable.strings
  Adyen/Assets/el-GR.lproj/Localizable.strings
  Adyen/Assets/en-US.lproj/Localizable.strings
  Adyen/Assets/es-ES.lproj/Localizable.strings
  Adyen/Assets/et-EE.lproj/Localizable.strings
  Adyen/Assets/fi.lproj/Localizable.strings
  Adyen/Assets/fr-FR.lproj/Localizable.strings
  Adyen/Assets/hr-HR.lproj/Localizable.strings
  Adyen/Assets/hu-HU.lproj/Localizable.strings
  Adyen/Assets/is-IS.lproj/Localizable.strings
  Adyen/Assets/it-IT.lproj/Localizable.strings
  Adyen/Assets/ja-JP.lproj/Localizable.strings
  Adyen/Assets/ko.lproj/Localizable.strings
  Adyen/Assets/lt-LT.lproj/Localizable.strings
  Adyen/Assets/lv-LV.lproj/Localizable.strings
  Adyen/Assets/nb-NO.lproj/Localizable.strings
  Adyen/Assets/nl-NL.lproj/Localizable.strings
  Adyen/Assets/pl-PL.lproj/Localizable.strings
  Adyen/Assets/pt-BR.lproj/Localizable.strings
  Adyen/Assets/pt-PT.lproj/Localizable.strings
  Adyen/Assets/ro-RO.lproj/Localizable.strings
  Adyen/Assets/ru-RU.lproj/Localizable.strings
  Adyen/Assets/sk-SK.lproj/Localizable.strings
  Adyen/Assets/sl-SI.lproj/Localizable.strings
  Adyen/Assets/sv-SE.lproj/Localizable.strings
  Adyen/Assets/zh-CN.lproj/Localizable.strings
  Adyen/Assets/zh-TW.lproj/Localizable.strings
  Adyen/UI/Form/Items/FormItemView.swift
  Adyen/UI/Form/Items/Value/Validatable/FormValidatableValueItemView.swift
  Adyen/Utilities/Observable/AdyenObservable.swift
  AdyenCard/Form/FormCardExpiryDateItem.swift
  AdyenCard/Form/FormCardSecurityCodeItemView.swift
  Tests/IntegrationTests/Card Tests/Views/FormCardExpiryDateItemViewTests.swift
Labels: fixed

#2154 SPI Documentation
  .spi.yml
Labels: chore

#2158 Stop plist file generation for `AdyenCardScanner`
  Adyen.xcodeproj/project.pbxproj
Labels: chore

#2157 DSP-2591: On cancel don't prompt for passkey enrollment
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
  AdyenActions/Components/3DS2/Action handlers/3DS2+Delegated Authentication/ThreeDS2PlusDACoreActionHandler.swift
  Tests/IntegrationTests/Card Tests/3DS2 Component/ThreeDS2PlusDACoreActionHandlerTests.swift
Labels: fixed

#2159 Fixed top, bottom margin and separator in coBadged card view and added separator in the UPI component list
  Adyen/UI/Form/Items/SelectableFormItem/SelectableFormItem.swift
  Adyen/UI/Form/Items/SelectableFormItem/SelectableFormItemStyle.swift
  Adyen/UI/Form/Items/SelectableFormItem/SelectableFormItemView.swift
  AdyenCard/Form/FormCoBadgedCardItem.swift
  AdyenCard/Form/FormCoBadgedCardItemView.swift
  AdyenComponents/UPI/UPIComponent.swift
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIConfiguration-iPad13-18-iPadOS_18-1-ar_AE.UI_configuration.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIConfiguration-iPad13-18-iPadOS_18-1-de_DE.UI_configuration.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIConfiguration-iPad13-18-iPadOS_18-1-en_US.UI_configuration.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIConfiguration-iPhone17-3-iOS_18-1-ar_AE.UI_configuration.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIConfiguration-iPhone17-3-iOS_18-1-de_DE.UI_configuration.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIConfiguration-iPhone17-3-iOS_18-1-en_US.UI_configuration.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPad13-18-iPadOS_18-1-ar_AE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPad13-18-iPadOS_18-1-de_DE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPad13-18-iPadOS_18-1-en_US.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPhone17-3-iOS_18-1-ar_AE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPhone17-3-iOS_18-1-de_DE.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUIElementsForPayByAnyUPIAppFlowType-iPhone17-3-iOS_18-1-en_US.all_required_fields_exist.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPad13-18-iPadOS_18-1-ar_AE.prefilled_vpa.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPad13-18-iPadOS_18-1-de_DE.prefilled_vpa.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPad13-18-iPadOS_18-1-en_US.prefilled_vpa.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPhone17-3-iOS_18-1-ar_AE.prefilled_vpa.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPhone17-3-iOS_18-1-de_DE.prefilled_vpa.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPICollectFlow-iPhone17-3-iOS_18-1-en_US.prefilled_vpa.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPIIntentFlow-iPad13-18-iPadOS_18-1-ar_AE.upi_intent.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPIIntentFlow-iPad13-18-iPadOS_18-1-de_DE.upi_intent.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPIIntentFlow-iPad13-18-iPadOS_18-1-en_US.upi_intent.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPIIntentFlow-iPhone17-3-iOS_18-1-ar_AE.upi_intent.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPIIntentFlow-iPhone17-3-iOS_18-1-de_DE.upi_intent.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/testUPIComponentDetailsForUPIIntentFlow-iPhone17-3-iOS_18-1-en_US.upi_intent.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPad13-18-iPadOS_18-1-ar_AE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPad13-18-iPadOS_18-1-de_DE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPad13-18-iPadOS_18-1-en_US.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPhone17-3-iOS_18-1-ar_AE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPhone17-3-iOS_18-1-de_DE.upi_no_app_selected_submit.png
  Tests/SnapshotTests/Components/__Snapshots__/UPIComponentUITests/test_noAppSelectedSubmit_shouldShowError-iPhone17-3-iOS_18-1-en_US.upi_no_app_selected_submit.png
Labels: changed

#2165 Update README.md - add Swift package index badges
  README.md
Labels: chore
