Repository Adyen/adyen-ios, pull requests merged in 2025-01, with the labels that each got.

#1924 Replace 3rd party workflow actions with Github API to access labels and PR body
  .github/workflows/validate_pr_labels_and_release_notes.yml
Labels: chore

#1935 Update detect_api_changes.yml
  .github/workflows/detect_api_changes.yml
Labels: chore

#1931 Cashapp/Twint error events
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  AdyenCashAppPay/CashAppPayComponent.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests+Convenience.swift
  Tests/IntegrationTests/Actions Tests/ActionComponent/Twint/TwintSDKActionTests.swift
  Tests/IntegrationTests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
Labels: chore

#1919 Add highlight styling to list style
  Adyen/UI/List/ListCell.swift
  Adyen/UI/List/ListItemStyle.swift
Labels: changed

#1944 Disabling deprecated compatibility builds
  .github/workflows/build.yml
Labels: chore

#1947 Analytics in apple pay component
  AdyenComponents/Apple Pay/ApplePayComponent.swift
  Tests/IntegrationTests/Components Tests/Apple Pay/ApplePayComponentTests.swift
Labels: chore

#1949 Resolve some warnings
  AdyenActions/AdyenActionComponent.swift
  AdyenActions/Components/SDK/TwintSDKActionComponent.swift
  AdyenActions/UI/View Controllers/DelegatedAuthentication/DelegatedAuthenticationView.swift
Labels: chore

#1954 Auto-focus first Text Field in Address Input Form
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/Form/Items/Basic Items/FormVerticalStackItemView.swift
  AdyenCard/Form/FormCardNumberContainerItem.swift
  AdyenCard/Form/FormCardNumberContainerItemView.swift
Labels: chore

#1952 ApplePayComponent: Make sure render event is called once
  AdyenComponents/Apple Pay/ApplePayComponent.swift
  Tests/IntegrationTests/Components Tests/Apple Pay/ApplePayComponentTests.swift
Labels: chore

#1957 [PAD] Removing fork check
  .github/workflows/detect_api_changes.yml
Labels: chore

#1959 Update `readme.md` with the link to versioning documentation
  README.md
Labels: chore

#1948 Fix broken CI workflows (v4)
  .github/workflows/build.yml
  .github/workflows/format_project.yml
  .github/workflows/pr_scan.yml
  .github/workflows/publich_podspec.yml
  .github/workflows/publish-demo-app.yml
  .github/workflows/regenerate-docs.yml
  .github/workflows/spell-check.yml
  .github/workflows/test-SPM-integration.yml
  .github/workflows/test-carthage-integration.yml
  .github/workflows/test_cocoapods_integration.yml
  .github/workflows/update-version.yml
  Adyen.xcodeproj/project.pbxproj
  Adyen/Core/Components/Base/Component.swift
  Adyen/Core/Components/Base/PaymentComponent.swift
  Adyen/Helpers/UIViewAnimation.swift
  Adyen/UI/Form/Items/Address/AddressViewModel.swift
  Adyen/Utilities/Coder.swift
  Adyen/Utilities/Observable/Observer.swift
  AdyenActions/Components/3DS2/ThreeDS2ComponentFingerprint.swift
  AdyenEncryption/Extensions/JSONEncoder+SortedKeys.swift.swift
  AdyenEncryption/JOSE/Encryption Algorithms/JSON Web Encryption/JSONWebEncryptionGenerator.swift
  AdyenEncryption/Payload/Payload.swift
  Demo/Common/Configuration/ConfigurationView.swift
  Demo/Common/Helpers/APIClientHelper.swift
  Scripts/carthage.sh
  Scripts/test-CocoaPods-integration.sh
  Scripts/test-carthage-integration.sh
  Tests/AdyenTests/Adyen Tests/Utilities/CoderTests.swift
  Tests/AdyenTests/Card Tests/3DS2 Component/ThreeDS2ClassicActionHandlerTests.swift
  Tests/AdyenTests/Card Tests/CardComponentTests.swift
  Tests/AdyenTests/Card Tests/Utilities/CardEncryptorCardTests.swift
Labels: chore

#1879 COIOS-802: Identify native redirect flow (v5)
  AdyenActions/Actions/Action.swift
  AdyenActions/Actions/RedirectAction.swift
  AdyenActions/Components/Redirect/RedirectComponent.swift
  Tests/IntegrationTests/Actions Tests/Redirect/RedirectComponentTests.swift
Labels: new

#1886 COIOS-812: Identify native redirect flow (v4)
  AdyenActions/Actions/RedirectAction.swift
  AdyenActions/Components/Redirect/RedirectComponent.swift
  Tests/AdyenTests/Adyen Tests/Components/Redirect/RedirectComponentTests.swift
Labels: new

#1960 Coios 855 3ds2 cancel update
  AdyenActions/Components/3DS2/Action handlers/3DS2 Without Delegated Authentication/ThreeDS2CoreActionHandler.swift
Labels: changed

#1963 Add accessibility identifier to Apple Pay pre-page root view
  AdyenDropIn/Views/PreApplePayView.swift
Labels: chore

#1967 Clean workflows
  .github/workflows/format_project.yml
  .github/workflows/prepare_release.yml
  .github/workflows/publish_podspec.yml
Labels: chore

#1962 Prepare Release Workflow
  .github/workflows/build.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/get_release_notes.yml
  .github/workflows/post_release.yml
  .github/workflows/prepare_release.yml
  .github/workflows/publish-demo-app.yml
  .github/workflows/publish_podspec.yml
Labels: chore

#1970 Fixed VoucherComponent doc
  AdyenActions/Components/Voucher/VoucherComponent.swift
Labels: chore

#1975 Restoring Compatibility Tests
  .github/workflows/verify-older-os-compatibility.yml
  README.md
  Scripts/test-carthage-integration.sh
Labels: chore

#1988 Trigger release workflow
  .github/workflows/create_release.yml
  .github/workflows/validate_pr_labels_and_release_notes.yml
Labels: chore

#1999 Release note workflow escaping
  .github/workflows/get_release_notes.yml
  .github/workflows/prepare_release.yml
Labels: chore
