Repository Adyen/adyen-ios, pull requests merged in 2025-02, with the labels that each got.

#2006 Initial UI setup
  Adyen.xcodeproj/project.pbxproj
  AdyenComponents/PayTo/PayToComponent.swift
  Tests/IntegrationTests/Components Tests/PayTo/PayToComponentTests.swift
  Tests/SnapshotTests/Components/PayToComponentUITests.swift
  Tests/UnitTests/Core/PaymentMethodTests.swift
  spell-check-word-allow-list.yaml
Labels: new

#2003 OCR: Card image parser
  Adyen.xcodeproj/project.pbxproj
  AdyenCardScanner/AdyenCardScanner.h
  AdyenCardScanner/Sources/CardImageParser.swift
  AdyenCardScanner/Sources/Formatters/ExpirationDateFormatter.swift
  AdyenCardScanner/Sources/Models/CardScannerError.swift
  AdyenCardScanner/Sources/Models/CreditCard.swift
  AdyenCardScannerTests/AdyenCardScannerTests.swift
Labels: chore

#2011 Removing release_notes.md
  .github/workflows/pr_scan.yml
  release_notes.md
Labels: chore

#2013 PayTo: Phone number item
  Adyen/UI/Form/Items/Phone Number/Phone Extension Picker/FormPhoneExtensionPickerItem.swift
  Adyen/UI/Form/Items/Phone Number/Phone Extension Picker/FormPhoneExtensionPickerItemView.swift
  Adyen/Utilities/External/PhoneExtensionsRepository.swift
  AdyenComponents/PayTo/PayToComponent.swift
  Tests/IntegrationTests/Card Tests/Items/CardNumberItem/FormItemViewBuilderTests.swift
  Tests/IntegrationTests/Components Tests/PayTo/PayToComponentTests.swift
Labels: chore

#2012 PayID tab UI elements
  Adyen.xcodeproj/project.pbxproj
  Adyen/UI/Form/Items/Value Pickers/Identifier Picker/FormStringPickerItem.swift
  AdyenComponents/PayTo/PayToComponent.swift
  Tests/IntegrationTests/Components Tests/PayTo/PayToComponentTests.swift
  spell-check-word-allow-list.yaml
Labels: new

#2016 Updating AdyenNetworking to 3.0.0
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/Requests/AnalyticsRequest.swift
  Adyen/Analytics/Requests/InitialAnalyticsRequest.swift
  Adyen/Core/APIClient/Requests/AppleWalletPassRequest.swift
  Adyen/Core/APIClient/Requests/ClientKeyRequest.swift
  Adyen/Core/APIClient/Requests/OrderStatusRequest.swift
  Adyen/Core/APIClient/Requests/PaymentStatusRequest.swift
  AdyenActions/Components/Redirect/NativeRedirectResultRequest.swift
  AdyenSession/API/Disable Stored Payments/DisableStoredPaymentMethodRequest.swift
  AdyenSession/API/Partial Payments API/Balance check/BalanceCheckRequest.swift
  AdyenSession/API/Partial Payments API/Cancel Order/CancelOrderRequest.swift
  AdyenSession/API/Partial Payments API/Create Order/CreateOrderRequest.swift
  AdyenSession/API/Payment Details/PaymentDetailsRequest.swift
  AdyenSession/API/Payments/PaymentsRequest.swift
  AdyenSession/API/Session Setup/SessionSetupRequest.swift
  Package.swift
  Scripts/generate_docc_documentation.sh
Labels: changed

#2018 Update create_release.yml
  .github/workflows/create_release.yml
Labels: chore

#2019 Fix prepare release script
  .github/workflows/get_release_notes.yml
  .github/workflows/prepare_release.yml
  .gitignore
Labels: chore

#2008 Card scanner module - Business layer
  Adyen.xcodeproj/project.pbxproj
  AdyenCardScanner/Sources/CaptureSessionManager.swift
  AdyenCardScanner/Sources/CardScannerOverlayView.swift
  AdyenCardScanner/Sources/CardScannerViewController.swift
  AdyenCardScanner/Sources/CardScannerViewModel.swift
  AdyenCardScanner/Sources/Extensions/AVCaptureVideoOrientation+Extensions.swift
  AdyenCardScanner/Sources/ROIView.swift
  spell-check-word-allow-list.yaml
Labels: chore

#2024 Payto: segment UI element and UI logic
  Adyen/UI/Form/Items/Value Pickers/Identifier Picker/FormStringPickerItem.swift
  AdyenComponents/PayTo/PayToComponent.swift
  Tests/IntegrationTests/Components Tests/PayTo/PayToComponentTests.swift
  spell-check-word-allow-list.yaml
Labels: chore

#2030 Payto items provider
  Adyen.xcodeproj/project.pbxproj
  AdyenComponents/PayTo/PayToComponent.swift
  AdyenComponents/PayTo/PayToItemsProvider.swift
  AdyenComponents/PayTo/PayToPayIdentifier.swift
Labels: chore

#2029 AdyenCardScanner - Public API
  Adyen.xcodeproj/project.pbxproj
  AdyenCardScanner/Sources/CaptureSessionManager.swift
  AdyenCardScanner/Sources/CardScanner.swift
  AdyenCardScanner/Sources/CardScannerAssembler.swift
  AdyenCardScanner/Sources/CardScannerViewController.swift
  AdyenCardScanner/Sources/CardScannerViewModel.swift
Labels: chore
