Repository Adyen/adyen-ios, pull requests merged in 2025-08, with the labels that each got.

#2185 fix: fix crash while presenting viewController
  Adyen.xcodeproj/project.pbxproj
  AdyenSwiftUI/Present View Controller/FullScreenViewControllerPresenter.swift
  Tests/UnitTests/AdyenSwiftUI/Present View Controller/FullScreenViewControllerTests.swift
  Tests/UnitTests/AdyenSwiftUI/Present View Controller/TestPresentingView.swift
Labels: fixed

#2193 Use .xcconfig file to store secrets
  .github/workflows/publish-demo-app.yml
  .gitignore
  Adyen.xcodeproj/project.pbxproj
  Demo/Configuration+secrets.swift
  Demo/Configuration.swift
  Demo/Secrets.template.xcconfig
  Demo/Secrets.xcconfig
  Demo/UIKit/Info.plist
  Scripts/publish-demo-app.sh
  Scripts/test-carthage-integration.sh
  spell-check-word-allow-list.yaml
Labels: chore

#2202 blik component v6 example on advanced flow
  Adyen.xcodeproj/project.pbxproj
  Adyen/Analytics/Models/AdyenAnalytics.swift
  Adyen/ResponseModels/CheckoutPaymentsResponse.swift
  AdyenCheckout/AdyenCheckout+DelegateCallbacks.swift
  AdyenCheckout/AdyenCheckoutComponent.swift
  AdyenComponents/Apple Pay/ApplePayComponent.swift
  AdyenComponents/Apple Pay/ApplePayComponentError.swift
  Demo/Common/IntegrationExamples/Components/BLIKComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataAdvancedFlowProtocol.swift
  Demo/Common/IntegrationExamples/Protocols/InitialDataFlowProtocol.swift
  Demo/Common/Networking/PaymentsRequest.swift
  Demo/Configuration.swift
  Demo/UIKit/ComponentsViewController.swift
Labels: chore, v6

#2211 Refelct latest changes in secrets management in Demo/README.md
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/IntegrationExamples/AdvancedFlow/Components/ApplePayComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/AdvancedFlow/Components/CardComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/AdvancedFlow/Components/InstantPaymentComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/AdvancedFlow/Components/IssuerListComponentAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/AdvancedFlow/DropIn/DropInAdvancedFlowExample.swift
  Demo/Common/IntegrationExamples/Session/Components/ApplePayComponentExample.swift
  Demo/Common/IntegrationExamples/Session/Components/CardComponentExample.swift
  Demo/Common/IntegrationExamples/Session/Components/InstantPaymentComponentExample.swift
  Demo/Common/IntegrationExamples/Session/Components/IssuerListComponentExample.swift
  Demo/Common/IntegrationExamples/Session/DropIn/DropInExample.swift
  Demo/README.md
Labels: chore

#2212 Specify permissions for github workflows
  .github/workflows/cancel-duplicate-work-flows.yml
  .github/workflows/create_release.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/detect_api_changes.yml
  .github/workflows/get_release_notes.yml
  .github/workflows/post_release.yml
  .github/workflows/pr_scan.yml
  .github/workflows/prepare_release.yml
  .github/workflows/publish-demo-app.yml
  .github/workflows/publish_podspec.yml
  .github/workflows/regenerate-docs.yml
  .github/workflows/regenerate-snapshots.yml
  .github/workflows/sdk_size_analysis.yml
  .github/workflows/spell-check.yml
  .github/workflows/stale_issues.yml
  .github/workflows/test-SPM-integration.yml
  .github/workflows/test-carthage-integration.yml
  .github/workflows/test_cocoapods_integration.yml
  .github/workflows/test_library_evolution.yml
  .github/workflows/update-version.yml
  .github/workflows/validate_pr_labels_and_release_notes.yml
  .github/workflows/verify-os-compatibility.yml
Labels: chore

#2216 Update generate snapshot action
  .github/workflows/regenerate-snapshots.yml
Labels: chore

#2209 COSDK-602: Update CodeQL Analysis [Swift analysis]
  .github/workflows/codeql.yml
Labels: chore

#2218 Switch to async/await for adyencheckout/session
  AdyenCheckout/AdyenCheckout.swift
  AdyenCheckout/AdyenCheckoutProtocol.swift
  AdyenCheckout/AdyenCheckoutProvider.swift
  AdyenSession/AdyenSession+PaymentComponentDelegate.swift
  AdyenSession/AdyenSession.swift
  Demo/Common/IntegrationExamples/AdvancedFlow/Components/BLIKComponentAdvancedFlowExample.swift
  Tests/IntegrationTests/Session Tests/SessionTests.swift
  Tests/UnitTests/AdyenCheckout/AdyenCheckoutProviderMock.swift
  Tests/UnitTests/AdyenCheckout/AdyenCheckoutTests.swift
Labels: chore, v6

#2226 Clarify `xcconfig` management in readme.md
  Demo/README.md
Labels: chore

#2199 Introducing theme manager for styling
  Adyen.xcodeproj/project.pbxproj
  Adyen/CheckoutConfiguration/CheckoutConfigurable.swift
  Adyen/CheckoutConfiguration/CheckoutConfiguration.swift
  Adyen/Helpers/UIViewRoundingHelpers.swift
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/Form/Items/Basic Items/FormLabelItem.swift
  Adyen/UI/Form/Items/Button/FormButtonItem.swift
  Adyen/UI/Form/Items/Button/FormButtonItemStyle.swift
  Adyen/UI/Form/Items/Button/FormButtonItemView.swift
  Adyen/UI/Form/Items/Error/FormErrorItemStyle.swift
  Adyen/UI/Styles/ButtonStyle.swift
  Adyen/UI/Styles/ImageStyle.swift
  Adyen/UI/Styles/TextStyle.swift
  Adyen/UI/View Controllers/SecuredViewController.swift
  Adyen/UI/Views/SubmitButton.swift
  AdyenActions/UI/UI Style/QRCodeComponentStyle.swift
  AdyenActions/UI/View Controllers/QR Code/QRCodeViewModel.swift
  AdyenActions/UI/View Controllers/Voucher/ShareableVoucherView.swift
  AdyenActions/UI/View Controllers/Voucher/VoucherViewModel.swift
  AdyenCheckout/AdyenCheckout.swift
  AdyenCheckout/AdyenCheckoutComponent.swift
  AdyenCheckout/CheckoutComponentBuilder.swift
  AdyenCheckout/Info.plist
  AdyenComponents/BLIK/BLIKComponent.swift
  AdyenComponents/BLIK/BLIKComponentConfiguration.swift
  AdyenComponents/SEPA Direct Debit/SEPADirectDebitComponent.swift
  AdyenDropIn/Models/DropInConfiguration.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
  AdyenUI/AdyenColorScheme.swift
  AdyenUI/AdyenFonts.swift
  AdyenUI/AdyenTheme.swift
  AdyenUI/AdyenUIConstants.swift
  AdyenUI/DefaultColors.swift
  AdyenUI/Helpers/UIColor.swift
  AdyenUI/Helpers/UIFont.swift
  AdyenUI/Info.plist
  AdyenUI/Styles/AdyenButtonStyles.swift
  AdyenUI/Styles/AdyenLabelStyle.swift
  AdyenUI/Styles/CornerRadiusStyle.swift
  Demo/Configuration.swift
  Package.swift
  Tests/IntegrationTests/Card Tests/CardComponentTests.swift
  Tests/IntegrationTests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/IntegrationTests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/IntegrationTests/Components Tests/Qiwi Wallet/QiwiWalletComponentTests.swift
  Tests/IntegrationTests/Components Tests/SEPA Tests/SEPADirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/Seven Eleven Component/BasicPersonalInfoFormComponentTests.swift
  Tests/IntegrationTests/DropIn Tests/PreselectedPaymentComponentTests.swift
  Tests/IntegrationTests/Helpers/XCTestCase+Style.swift
  Tests/UnitTests/AdyenTheme/AdyenThemeTests.swift
Labels: chore, v6

#2229 Update 3ds2 sdk release version 2.4.3
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Package.swift
  Scripts/generate_docc_documentation.sh
  Scripts/test-CocoaPods-integration.sh
Labels: changed, chore

#2231 V4_Update 3ds2 sdk release version 2.4.3
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  AdyenCard/Components/Card/ThreeDS2SdkVersion.swift
  Cartfile
  Cartfile.resolved
  Package.swift
Labels: chore

#2237 Update AdyenCardScanner podspec
  AdyenCardScanner.podspec
Labels: chore

#2234 Update post_release.yml to include write access
  .github/workflows/deploy-docs.yml
  .github/workflows/post_release.yml
  .github/workflows/prepare_release.yml
  .github/workflows/publish_podspec.yml
Labels: chore
