Repository Adyen/adyen-ios, pull requests merged in 2025-05, with the labels that each got.

#2103 Introducing package access modifier
  Adyen.podspec
  Adyen.xcodeproj/project.pbxproj
  Adyen/CheckoutConfiguration/CheckoutBaseCallbacks.swift
  Adyen/CheckoutConfiguration/CheckoutComponentType.swift
  Adyen/CheckoutConfiguration/CheckoutConfigurable.swift
  Adyen/CheckoutConfiguration/CheckoutConfiguration+Callbacks.swift
  Adyen/CheckoutConfiguration/CheckoutConfiguration.swift
  Adyen/CheckoutConfiguration/ConfigurationBuilder.swift
  Adyen/Core/APIClient/APIContext.swift
  AdyenCheckout/AdyenCheckout.swift
  AdyenCheckout/AdyenCheckoutProtocol.swift
  AdyenCheckout/CheckoutComponentBuilder.swift
  AdyenComponents/BLIK/BLIKComponentConfiguration.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
  Package.swift
  Scripts/test-SPM-integration.sh
Labels: chore

#2107 README for AdyenCardScanner
  Adyen.xcodeproj/project.pbxproj
  AdyenCardScanner/Images/plist-file-demo.png
  AdyenCardScanner/README.md
  AdyenCardScanner/Sources/CardScanner.swift
Labels: chore

#2108 Allow overrides whed using "enforce locale"
  Adyen.xcodeproj/project.pbxproj
  Adyen/Utilities/Localization.swift
  Adyen/Utilities/LocalizationParameters.swift
  Demo/SwiftUI/Info.plist
  Demo/SwiftUI/hi.lproj/LaunchScreen.strings
  Demo/UIKit/hi.lproj/LaunchScreen.strings
  Tests/IntegrationTests/Localization/Assets/hi.lproj/EnforceLocaleTests.strings
  Tests/IntegrationTests/Localization/Assets/is-IS.lproj/EnforceLocaleTests.strings
  Tests/IntegrationTests/Localization/Assets/ro-RO.lproj/EnforceLocaleTests.strings
  Tests/IntegrationTests/Localization/LocalizationTests.swift
Labels: new

#2111 Improve localization
  Adyen.docc/Assets/localization_diagram.png
  Adyen.docc/Localization.md
  Adyen.xcodeproj/project.pbxproj
  Demo/Common/Assets/Localizable.strings
  Demo/Common/Assets/Localizable.xcstrings
  Tests/IntegrationTests/Localization/Assets/Localizable.strings
  Tests/IntegrationTests/Localization/Assets/Localizable.xcstrings
  Tests/IntegrationTests/Localization/Assets/hi.lproj/EnforceLocaleTests.strings
  Tests/IntegrationTests/Localization/Assets/is-IS.lproj/EnforceLocaleTests.strings
  Tests/IntegrationTests/Localization/LocalizationTests.swift
Labels: chore

#2120 CardScanner: Focus on CVC field after successful scan
  Adyen/Core/APIClient/APIContext.swift
  Adyen/Core/AdyenContext/AdyenContext.swift
  Adyen/UI/Form/FormViewController+ViewProtocol.swift
  Adyen/UI/Form/FormViewController.swift
  Adyen/UI/Form/Items/Text/FormTextInputItem.swift
  Adyen/UI/Form/Items/Text/FormTextInputItemView.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  AdyenCard/Components/Card/CardScannerController.swift
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Components/Card/DummyCardScannerController.swift
  AdyenCard/Form/FormCardExpiryDateItem.swift
  AdyenCard/Form/FormCardSecurityCodeItem.swift
  AdyenCard/Form/FormCardSecurityCodeItemView.swift
  Tests/IntegrationTests/Card Tests/BCMCComponentTests.swift
  Tests/IntegrationTests/Card Tests/Card Scanner/CardScannerControllerTests.swift
  Tests/IntegrationTests/Card Tests/CardComponentEventTests.swift
  Tests/IntegrationTests/Card Tests/CardComponentTests.swift
  Tests/IntegrationTests/Card Tests/FormViewControllerTests.swift
  Tests/IntegrationTests/Components Tests/Gift Card/GiftCardComponentTests.swift
Labels: chore

#2122 Remove CardScanning protocol
  AdyenCardScanner/Sources/CardScanner.swift
Labels: chore

#2128 Fix: `cancel-duplicate-work-flows` job stuck in "in-progress" state
  .github/workflows/cancel-duplicate-work-flows.yml
Labels: chore

#2132 Enable manual action trigger for integrations
  .github/workflows/test-SPM-integration.yml
  .github/workflows/test-carthage-integration.yml
  .github/workflows/test_cocoapods_integration.yml
Labels: chore

#2134 Fix selector mock
  Tests/IntegrationTests/Card Tests/Items/CardNumberItem/FormCardNumberItemViewTests.swift
Labels: chore

#2135 Renamed variable
  AdyenCard/Components/Card/CardViewController.swift
  AdyenCard/Form/FormCoBadgedCardItem.swift
  Tests/IntegrationTests/Card Tests/CardComponentTests.swift
Labels: chore

#2119 v6: super component callbacks
  Adyen.xcodeproj/project.pbxproj
  Adyen.xcodeproj/xcshareddata/xcschemes/AdyenUIHost.xcscheme
  Adyen/Actions/Action.swift
  Adyen/Actions/AnyVoucherAction.swift
  Adyen/Actions/AwaitAction.swift
  Adyen/Actions/BoletoVoucherAction.swift
  Adyen/Actions/DocumentAction.swift
  Adyen/Actions/DokuVoucherAction.swift
  Adyen/Actions/EContextATMVoucherAction.swift
  Adyen/Actions/EContextStoresVoucherAction.swift
  Adyen/Actions/MultibancoVoucherAction.swift
  Adyen/Actions/OXXOVoucherAction.swift
  Adyen/Actions/QRCodeAction.swift
  Adyen/Actions/RedireactableAwaitAction.swift
  Adyen/Actions/RedirectAction.swift
  Adyen/Actions/SDKAction.swift
  Adyen/Actions/ThreeDS2Action.swift
  Adyen/Actions/ThreeDS2ChallengeAction.swift
  Adyen/Actions/ThreeDS2FingerprintAction.swift
  Adyen/Actions/TwintSDKAction.swift
  Adyen/Actions/TwintSDKData.swift
  Adyen/Actions/VoucherAction.swift
  Adyen/Actions/WeChatPaySDKAction.swift
  Adyen/Actions/WeChatPaySDKData.swift
  Adyen/CheckoutConfiguration/CheckoutBaseCallbacks.swift
  Adyen/CheckoutConfiguration/CheckoutConfiguration.swift
  Adyen/ResponseModels/CheckoutPaymentsResponse.swift
  Adyen/ResponseModels/CheckoutResultCode.swift
  Adyen/UI/Form/FormViewController+ViewProtocol.swift
  Adyen/UI/Form/Items/Text/FormTextItemView.swift
  AdyenActions/Components/Await/PollingHandlerProvider.swift
  AdyenCheckout/AdyenCheckout.swift
  AdyenCheckout/AdyenCheckoutComponent.swift
  AdyenCheckout/AdyenCheckoutProtocol.swift
  AdyenCheckout/CheckoutComponentBuilder.swift
  AdyenDropIn/Utilities/ComponentManager+PaymentComponentBuilder.swift
  Scripts/test-CocoaPods-integration.sh
  Tests/IntegrationTests/Actions Tests/Voucher/VoucherViewTests.swift
  Tests/IntegrationTests/Card Tests/CardComponentTests.swift
  Tests/IntegrationTests/Components Tests/ACH Direct Debit/ACHDirectDebitComponentTests.swift
  Tests/IntegrationTests/Components Tests/BACS Direct Debit/Trackers/BACSDirectDebitComponentTrackerTests.swift
  Tests/IntegrationTests/Components Tests/BLIK Component/BLIKComponentTests.swift
  Tests/IntegrationTests/Components Tests/Cash App Pay/CashAppPayComponentTests.swift
  Tests/IntegrationTests/Components Tests/Online Banking/OnlineBankingComponentTests.swift
  Tests/IntegrationTests/Components Tests/PayTo/PayToComponentTests.swift
  Tests/SnapshotTests/Components/BLIKComponentUITests.swift
  Tests/SnapshotTests/Components/BoletoComponentUITests.swift
  Tests/SnapshotTests/Components/OnlineBankingComponentUITests.swift
  Tests/UnitTests/Core/ActionTests.swift
  Tests/UnitTests/Core/AdyenContextTests.swift
  Tests/UnitTests/DropIn/ComponentManagerTests.swift
  Tests/UnitTests/Mocks/DummyData/Dummy.swift
  Tests/UnitTests/Mocks/DummyData/DummyHelper.swift
Labels: chore, v6

#2139 CI - introduce SDK size checks
  .github/workflows/sdk_size_analysis.yml
  Adyen.xcodeproj/project.pbxproj
  Scripts/sdk_size_analysis.sh
Labels: chore
